const articles = [{
  title: 'Transfert : Memphis Depay (Manchester United) est arrivé à Lyon',
  content: `Un tweet accompagné d'une photo. L'OL a annoncé mercredi soir l'arrivée entre Rhône et Saône de l'attaquant néerlandais de Manchester United Memphis Depay, 23 ans. Au fil de la journée, on avait appris la conclusion d'un accord entre les deux clubs sur le montant du transfert, puis Jean-Michel Aulas, le président lyonnais, avait confirmé cet accord. De source anglaise, le montant de la transaction s'élèverait à 25 M€. Dans son tweet, l'OL indique que le joueur sera rejoint jeudi par ses agents pour discuter de son contrat. Depay a été accueilli par Florian Maurice, responsable de la cellule de recrutement.`,
  author: 'Fabrice Roche',
  date: '2017-01-19',
  img: 'https://medias.lequipe.fr/img-photo-jpg/memphis-depay-a-t-accueilli-par-florian-maurice/1500000000779316/0:33,476:350-624-416-75/b782b.jpg',
  tags: ['sport', 'football', 'mercato'],
}, {
 title: 'Mort du chanteur et compositeur nigérian William Onyeabor',
 content: `En 2013, une compilation pertinemment baptisée Who Is William Onyeanor ?, publiée par Luaka Bop, label archiviste des musiques du monde, exhumait de l’oubli le chanteur, compositeur, producteur et homme d’affaires nigérian William Ezechukwu Onyeabor, étrange pionnier de la musique électronique africaine, qui se découvrait à l’occasion une nouvelle cohorte de fans, parmi lesquels Damon Albarn, l’ancien Talking Heads David Byrne (fondateur, en 1988, de Luaka Bop), les groupes Hot Chip ou LCD Sound System…
Sans jamais avoir accepté de participer aux concerts hommages organisés à la suite de cette publication, ni avoir répondu aux demandes d’interview, le musicien a continué d’habiter sa ville d’Enugu, au sud-est du Nigéria, jusqu’à sa mort, le 16 janvier, à l’âge de 70 ans.

Pasteur de l’église Born Again
« Nous ne savions pas grand chose sur William Onyeabor au moment de commencer ce disque et nous n’en savons pas beaucoup plus aujourd’hui » avait déclaré au Monde, Yale Evelev, le président de Luaka Bop. Si l’équipe du label avait fini par retrouver le monsieur et entretenait avec lui des relations cordiales, les questions sur son histoire étaient le plus souvent accueillies par ce pasteur de l’église Born Again par un énigmatique : « Je veux seulement parler de Dieu ».
Entre 1977 et 1985, Onyeabor avait pourtant autoproduit neuf albums, tous enregistrés et pressés dans son propre studio de Wilfilms Ltd, à Enugu. Il aurait eu au départ des velléités de producteur de cinéma, aurait composé ses premiers morceaux comme bande originale d’un film.
Damon Albarn, leader de Blur et de Gorillaz : « Cela ne ressemble à rien et semble si moderne. C’est excentrique, intelligent et incroyablement funky »
A l’époque, le pays confirme son statut de vivier musical majeur de l’Afrique de l’Ouest. L’ancienne colonie britannique, indépendante depuis 1960, a notamment vu l’effervescence la gagner après le boom pétrolier qui suivit la fin de la guerre du Biafra (1967-1970). Parmi les héros de styles locaux comme la juju music, le high-life ou l’afrobeat, fusions complexes de musiques traditionnelles et d’influences soul, rhythm’n’blues, jazz et rock, des figures internationales comme King Sunny Adé ou, bien sûr, Fela Kuti.
Contrastant avec l’instrumentation de ces artistes, les disques d’Onyeabor sont dominés par les synthétiseurs et une utilisation de l’électronique qui étonne encore aujourd’hui. « Cela ne ressemble à rien et semble si moderne. C’est excentrique, intelligent et incroyablement funky » s’enthousiasmait ainsi le leader de Blur et de Gorillaz, Damon Albarn, devant ce croisement improbable d’afrobeat et de pop à la Kraftwerk.

Entrepreneur dans l’agro-alimentaire
D’ou venaient ces synthétiseurs, si inaccessibles alors à la plupart des musiciens africains et si fragiles sous le climat tropical ? Selon certains, William Onyeabor avait étudié le cinéma à Moscou, pour d’autres, le droit à Oxford. Malgré quelques succès – When the Going is Smooth and Good –, le mystérieux chanteur refuse à l’époque les interviews et toute performance publique, en ermite des studios.
D’après le label Luaka Bop, qui l’a salué, le 17 janvier, dans un communiqué de condoléances, le musicien aurait voyagé en Europe à la fin des années 1970 pour en savoir plus sur la production industrielle de disques et constituer sa propre unité de pressage et d’impression. Après sa carrière musicale, William Onyeanor avait d’ailleurs continué à s’occuper d’affaires, investissant en particulier dans l’agro-alimentaire (il aurait été récompensé, en 1987, du titre d’entrepreneur ouest-africain de l’année !). Notable local, président du club de football des Enugu Rangers, ce chrétien Born Again ne voulait en tout cas plus entendre parler de musique. Au point de refuser toute participation aux différents concerts célébrant son hypnotique répertoire (Let’s Fall in Love, Good Name, Fantastic Man…), par le biais d’un plateau du nom de Atomic Bomb ! Who Is William Onyeabor ?, accueillant dans des salles et festivals internationaux des invités tels Damon Albarn, David Byrne, Sinkane, Ghostpoet, Alexis Taylor (de Hot Chip), Kele Okereke (de Bloc Party), Money Mark (des Beastie Boys) ou Pat Mahoney (de LCD Sound System).`,
 author: 'Stéphane Davet',
 date: '2017-01-19',
 img: 'http://s2.lemde.fr/image/2017/01/19/534x0/5065440_6_63db_le-chanteur-compositeur-producteur-et-homme_40fde1e943437b29c73495a67c27252a.jpg',
 tags: ['culture', 'musique'],
}, {
 title: 'Plongée dans l\'univers graphique des plantes vertes',
 content: `TENDANCE - Elles font leur grand retour dans les appartements à condition d'afficher un caractère fort et une silhouette structurée.
À Paris, sous le mur végétalisé de la rue d'Aboukir, a ouvert, cette année, un concept store dédié aux hommes. Signe des temps, après la mode, les accessoires, un barbier, des livres et de la musique, La Garçonnière vient d'installer dans ses murs un corner réservé aux plantes. Une nécessité parce que les hommes ne sont pas les derniers à mettre les mains dans la terre. Désormais, tout le monde y va de son petit coin de nature à domicile.
«Jusque dans les années 1990, il y avait une profusion de plantes vertes dans les maisons, rappelle Stéphane Frisson, responsable des achats de végétaux chez Jardiland. Puis est arrivée, à leur détriment, la déferlante des orchidées, notamment du Phalaenopsis sous toutes ses formes, la plante la plus vendue dans le monde, parce qu'elle est belle et extrêmement simple à entretenir. Cela s'est accompagné d'un décor épuré dans lequel l'orchidée fait figure d'objet de décoration à part entière. Pour la première fois, on assiste à une chute des ventes.»
«Langue de belle-mère»

Le Sansevieria ou «langue de belle-mère». Photo: Solvej Schou/AP/SIPA.
Selon le spécialiste, depuis l'année dernière - et la tendance viendrait comme souvent des pays du Nord -, les plantes vertes, très graphiques, ont le vent en poupe, «une demande forte qui a même surpris les producteurs». Ainsi le Sansevieria, qui doit à ses longues feuilles dressées d'être surnommé «langue de belle-mère», modernisé par des jeux de tressage. Mais aussi l'Aglaonema, au feuillage bien fourni marbré de rouge, jaune ou argent, ou encore le Pilea peperomioides, auquel des feuilles rondes comme des pastilles confèrent une silhouette gracieuse. Dans le registre des plantes graphiques, les caoutchoucs et autres Monstera, stars des années 1950-1960, font eux aussi une percée remarquée. «Ils sont remis au goût du jour par un choix variétal et possèdent un côté jungle qui coïncide avec les imprimés actuels des tissus et papiers peints, souligne Stéphane Frisson. On sent aussi venir, en courant de fond, les plantes grasses, les succulentes et les cactées.»
Des tout petits formats en plusieurs exemplaires

D'ailleurs, l'Office hollandais des fleurs, renifleur des tendances à venir qu'il partage dans des publications sur son site Maplantemonbonheur.fr, leur a consacré un livret. D'après l'OHF, les cactus apportent une touche arty aussi bien à l'extérieur qu'à l'intérieur, permettent de reconsidérer l'espace en le structurant et ils donnent du relief à la déco. Leurs quelque 1 800 espèces permettent de jouer à fond les formes, des coussins boules des Echinocactusjusqu'aux oreilles plates de Gymnocalycium en passant par les totems qui peuvent atteindre parfois plusieurs mètres de haut, des Cereus. Les tout petits formats rencontrent un beau succès, associés en plusieurs exemplaires de formes différentes. Sans doute parce que la miniaturisation -manque de place oblige- est dans l'air du temps. D'où la multiplication des terrariums, microjardins enfermés dans des contenants transparents, que l'on peut poser sur un meuble ou, pourquoi pas, suspendre comme un mobile.
Come-back des plantes retombantes

Le charme ébouriffé du Rhipsalis. Photo: Maplantemonbonheur.fr
À propos de suspensions, l'OHF croit beaucoup au come-back des plantes retombantes, à commencer par le Rhipsalis, un chevelu ébouriffé, les Gynura aux feuilles ourlées de mauve et l'Aeschynanthus, qui développe des fleurs aussi rouges qu'un lipstick. Serax et d'autres pros de la déco ont prévu le coup en imaginant des contenants adaptés: pour Serax, des sacs en toile blanche prêts à être accrochés au plafond, selon son bon vouloir. Une façon de mettre du vert chez soi sans encombrer les meubles. On l'aura compris, la plante ne se suffit pas à elle-même: «le couple qu'elle forme avec son pot ou son cache-pot donne le ton de la décoration, la mène vers la modernité.» Verre, matières rugueuses comme le béton, un tuteur original… les possibilités sont multiples. «On peut même, dans une composition, associer des pots de couleurs différentes, à condition qu'ils relèvent tous du même esprit», estime Stéphane Frisson.
Naturellement facile à vivre

Pour facilité la vie de futurs propriétaires pas toujours avertis, Stéphanie Reydellet, via sa start-up Mon Balcon Parisien, s'est particulièrement intéressée aux mousses, une espèce naturellement facile à vivre, dont elle simplifie encore l'entretien en remplaçant la sève naturelle par une substance biodégradable proche du sucre. Ainsi traitées, les mousses n'ont besoin de rien pour conserver leur fraîcheur, ni arrosage ni luminosité, et ont une durée de vie d'un an. Elle les présente dans des bonbonnières ou des bocaux qui s'emboîtent, associées parfois à de la fougère, mais dans ce cas un petit coup de brumisateur est nécessaire de temps en temps. «On peut y ajouter des pierres, des matières qui apportent de l'originalité tout en restant design.» Des plantes, oui, mais sans soucis.`,
 author: 'Catherine Saint-Jean',
 date: '2016-11-25',
 img: 'http://i.f1g.fr/media/figaro/805x453_crop/2016/11/25/XVM6ed6280a-b261-11e6-a0e2-b844a3b16519.jpg',
 tags: ['jardin', 'déco'],
}, {
 title: 'La France continue de vendre des armes à des pays sous embargo international',
 content: `Comme tous les membres des Nations-Unies et de l’Union européenne, la France est tenue de respecter les embargos votés sur les ventes d’armes. Elle aurait pourtant violé près de la moitié de ces embargos ces dernières années, selon une évaluation de l’Observatoire des armements, mise en carte ci-dessous. Et le gouvernement refuse de répondre aux interpellations de parlementaires sur le sujet. La loi érigeant en délit la violation des embargos est toujours en attente d’être votée au Sénat, dix ans après son premier examen...

Les premières intentions se voulaient nobles. La politique d’exportation d’armes doit être « rigoureuse dans ses principes », ainsi a déclaré Jean-Yves Le Drian en accédant au poste de ministre de la Défense en 2012. Une réforme du contrôle des exportations devait ensuite être menée. Dans les faits, un rapport a bien été rendu au Premier ministre, en 2013 [1]. Pour être aussitôt enterré.

Les exportations d’armes de la France sont ainsi restées d’une grande opacité. La plupart des informations proviennent des rapports annuels au Parlement, qui sont une source très incomplète : elles portent sur des autorisations et licences délivrées par l’État, qui ne garantissent en rien que le matériel ait été effectivement livré. Elles n’indiquent ni le détail des livraisons, ni les caractéristiques du matériel, ni leur destinataire précis – des données pourtant essentielles pour pouvoir certifier si un embargo international est respecté ou non.

Un demi-milliard d’euros de ventes à la Chine

Des dizaines de pays sont ainsi interdits de livraisons d’armement. La Libye, la Côte d’Ivoire, l’Iran, ou encore la République centrafricaine sont sous embargo, suite à des décisions du Conseil de sécurité des Nations-Unies. Le Soudan, le Soudan du Sud, la Syrie et la Chine sont sous embargo de l’Union européenne. Mais l’embargo européen sur les ventes d’armes à la Chine n’a pas empêché la France de fournir pour plus de 500 millions d’euros d’armements à Pékin entre 2010 et 2014.

Le gouvernement français, même lorsqu’il est sollicité par les parlementaires, se refuse à communiquer sur le sujet. En septembre 2015, la députée écologiste Danielle Auroi a demandé au ministre de la Défense les détails de plusieurs transactions suspectes à destination de la Libye. Le 15 octobre 2015, Jean-Yves Le Drian a démenti toute violation de l’embargo... tout en opposant le secret défense à la parlementaire. Une situation à comparer avec le Royaume-Uni, où l’information au Parlement constitue une obligation.

En pleine répression, des blindés pour l’Égypte

Comment prendre la parole du ministre pour argent comptant, quand il est établi que la France fournit régulièrement des armes à des groupes ou à des régimes peu fréquentables, en recourant aux services secrets ou, encore plus risqué, à des sociétés privées ? C’est ainsi que les sociétés Acmat Défense et le groupe Marck ont été épinglés par le groupe d’experts des Nations-Unies sur la Côte d’Ivoire pour de multiples violations de l’embargo sur ce pays en 2011 et 2012. Ces constructeurs ont pignon sur rue et sont présents au salon de l’armement Eurosatory, organisé tous les deux ans à Villepinte, au nord de Paris.

Il en est de même de la fourniture en juin 2016 de matériel militaire aux combattants kurdes d’Irak, transaction pourtant en principe interdite par l’embargo sur l’Irak – décidé en 2004 par la résolution 1546 des Nations Unies – qui n’autorise que l’équipement des forces gouvernementales ou multinationales. Quant à la livraison de blindés légers Renault à l’Égypte en 2013 et 2014 – en pleine répression – elle pose forcément question, le matériel en question entrant dans la catégorie visée par l’embargo européen.

Onze embargos violés ?

Les autorisations d’exportation sont la signature politique des ventes d’armes. Le manque de transparence vise à se soustraire de la norme internationale. Si l’État viole cette norme, il est difficile de le prouver en raison du manque d’éléments de preuve. Les informations (fragmentaires) dont nous disposons montrent cependant que le respect par Paris de près de la moitié (11) des 24 embargos édictés par l’ONU et l’Union européenne peut être mis en doute.

Face à cela, le contrôle démocratique est en panne. La loi érigeant en délit la violation des embargos est toujours en attente d’être votée au Sénat... dix ans après son premier examen. Faisant l’objet d’un actif plaidoyer de la part de l’Observatoire des armements, d’Amnesty International France et de l’association Survie depuis janvier 2015, le projet de loi est passé à l’Assemblée nationale en seconde lecture le 28 janvier 2016. La mouture originale a été considérablement renforcée par des députés écologistes et socialistes... avant de se retrouver une nouvelle fois bloquée par le gouvernement. Les calculs politiques et économiques de l’industrie de l’armement l’emportent une fois de plus.

Un vecteur d’influence

Cette loi permettrait pourtant de poursuivre les contrevenants, personnes (trafiquants et intermédiaires) comme entreprises, qui sont les premières concernées – selon le ministère de la Défense, 95% des autorisations d’intermédiation sont données à des personnes morales. Mais ce gouvernement, comme les précédents, refuse encore de donner à la justice les moyens de punir la violation des embargos. Nous restons ainsi dans une situation d’impuissance. Des embargos sont décidé, mais aucun instrument judiciaire ne force le gouvernement à les appliquer. Car les États font des transferts d’armes un vecteur d’influence sur la scène internationale. Les transferts dits légaux constituent la vitrine de cette politique ; les trafics d’armes, proscrits par les embargos, en sont la face cachée.

Il est difficile de s’y retrouver dans la jungle des embargos dont les modalités diffèrent fortement selon la destination visée. Ces mesures sont d’abord les variables d’ajustement des intérêts occidentaux. Alors que des armes vendues par la France comme les chars Leclerc (aux Émirats arabes unis), les Mirage 2000 (au Qatar) ou les canons d’artillerie Caesar (à l’Arabie saoudite) sont employées dans la guerre au Yémen, Paris échappe au radar du droit international.

Renforcer la norme internationale

Car l’embargo sur le Yémen ne s’applique qu’aux forces rebelles houthies et pas aux membres de la coalition en guerre (dont font partie, entre autres, l’Arabie saoudite, le Qatar, les Émirats arabes unis, l’Égypte), équipés par les grands pays exportateurs d’armes (États-Unis, Royaume-Uni, France, Canada). En outre, les embargos pesant sur des puissances comme la Chine ou l’Égypte ne sont pas contraignants. Une fois encore, le champ d’application des embargos dépend moins de la volonté d’épargner des morts civils que du poids géostratégique des parties en conflit.

Un tel panorama ne doit pas aboutir au discrédit de la norme internationale, il est au contraire nécessaire de chercher tous les moyens de la renforcer. Mais ce constat conduit à réinterroger la notion d’État de droit, qui est délibérément refusé aux populations vivant loin de chez nous, dont le droit de vie et de mort est en partie scellé par « le grand jeu » de la France avec les autres puissances.`,
 author: 'Tony Fortin, responsable de l’Observatoire des armements.',
 date: '2017-01-25',
 img: 'http://www.bastamag.net/IMG/arton5956.jpg?1483536790',
 tags: ['France', 'géopolitique', 'Défense'],
}, {
 title: 'Deutsche Bank, l’étoile déchue du capitalisme rhénan',
 content: `Un « casino géant » aux « dirigeants irresponsables ». Les hommes politiques allemands ne mâchent pas leurs mots quand ils parlent de Deutsche Bank. « Je ne sais pas s’il faut rire ou pleurer de voir une banque qui a fait de la spéculation un modèle de développement venir maintenant se poser en victime », a ainsi déclaré en octobre le ministre de l’Economie Sigmar Gabriel, alors que la première banque d’outre-Rhin se trouve sous la menace d’une amende record. Le ministère de la Justice américain lui réclame 14 milliards de dollars pour des faits remontant à l’époque des crédits subprime1. Ce montant était bien plus élevé que ne l’avaient anticipé les experts. Ce n’était cependant qu’une mauvaise nouvelle de plus pour le groupe germanique, qui se trouvait déjà dans une posture délicate.

Des amendes à la pelle
Car ce n’est pas la première affaire juridique dans laquelle Deutsche Bank est embourbée. Depuis 2008, le groupe basé à Francfort a déjà versé plus de 9 milliards de dollars pour des sanctions diverses liées à des manipulations de taux, de devises, de certificats de CO2, mais aussi pour des violations d’embargo avec l’Iran et la Syrie. Selon l’AFP, le nom de la banque est cité dans plus de 6 000 contentieux… A l’instar de son compatriote Volkswagen dans l’automobile, Deutsche Bank est devenu le paria de son secteur.

14 milliards de dollars, c’est le montant réclamé à la Deutsche Bank par le ministère de la Justice américain Twitter
Ces amendes à la pelle viennent amputer sérieusement ses profits au moment où la direction s’est lancée dans une coûteuse restructuration2 et a décidé de nettoyer les comptes en dépréciant3 certains actifs. Résultat : la banque a enregistré une mégaperte de près de 7 milliards d’euros en 2015.

Très engagée dans des activités de marché, telles que l’émission de produits dérivés ou le trading de devises, Deutsche Bank s’est également attiré les foudres des régulateurs bancaires. Elle a certes passé avec succès les tests de résistance de l’Autorité bancaire européenne (ABE), mais aux Etats-Unis, sa filiale a échoué pour la deuxième fois cet été aux « stress tests » imposés par la Réserve fédérale américaine. Plus grave encore, le Fonds monétaire international (FMI) a récemment exprimé ses craintes à l’égard de l’institution de Francfort, qui constitue, selon lui, « le plus important contributeur net aux risques systémiques au sein du secteur bancaire international ».

Vautours
Cette accumulation de mauvaises nouvelles ne rassure pas les investisseurs, qui ont massivement vendu leurs parts dans la société. L’action Deutsche Bank, qui valait plus de 100 euros en 2007, était tombée à 17 euros, six fois moins, début décembre. Pour ne rien arranger, les vautours rôdent… Des fonds spéculatifs ont vendu l’action à découvert4 avec l’espoir de réaliser de substantiels gains si la chute du titre se poursuit. Fin septembre, ces fonds dits « opportunistes » détenaient plus de 2 % du capital de la banque, contre 0,5 % quelques mois auparavant. « Certaines forces sur le marché veulent miner notre confiance en nous », s’est lamenté le directeur général John Cryan dans une lettre aux salariés.

Accompagnant les industriels dans leur croissance pénoménale, Deutsche Bank s’est enrichi et internationalisé avec eux Twitter
Comment le géant Deutsche Bank a-t-il pu se retrouver à ce point bousculé ? Un tel scénario aurait longtemps paru inimaginable. Créée en 1870, la vénérable institution s’était construit une solide réputation grâce à un positionnement gagnant : le financement d’une industrie allemande en plein essor. A l’instar de ses compatriotes Dresdner et Commerzbank, Deutsche Bank prenait des participations au capital des grandes entreprises avec lesquelles elle faisait affaire : Bayer, BASF, Krupp, Siemens, puis Lufthansa et Daimler. Le groupe francfortois siégeait donc au conseil de surveillance de ces champions nationaux. Il a profité à plein du système de la « Deutschland AG », basé sur ces participations croisées entre grandes entreprises allemandes. En accompagnant les industriels dans leur croissance phénoménale, il s’est enrichi et internationalisé avec eux.

La folie des grandeurs
Mais à partir des années 1980, l’ère du libéralisme va remettre en cause le modèle germanique de la « banque-industrie ». Confrontée à la concurrence des banques d’affaires anglo-saxonnes, qui courtisaient ses clients en leur proposant des produits financiers de plus en plus complexes, Deutsche Bank a répliqué et décidé de les affronter sur leur propre terrain. Pour cela, elle a fait l’acquisition de deux banques anglo-saxonnes : la britannique Morgan Grenfell en 1989 et, dix ans plus tard, l’américaine Bankers Trust.

Puis, au début du nouveau millénaire, le gouvernement de Gerhard Schröder a supprimé l’impôt sur les plus-values de cession à la demande des groupes financiers allemands sonnant ainsi le glas de la « Deutschland AG ». Deutsche Bank en a profité pour revendre toutes ses participations dans l’industrie allemande. Elle s’est résolument tournée vers les activités de marché. Le directeur de l’époque, Josef Ackermann, a promis aux actionnaires des niveaux de rentabilité très élevés, encourageant de fait ses équipes à prendre tous les risques pour les atteindre. Après la crise financière de 2008, Deutsche Bank mettra beaucoup plus de temps que ses concurrentes à réduire la voilure sur les activités spéculatives et à se recentrer sur les prêts classiques aux entreprises et aux particuliers.

John Cryan a changé la quasi-totalité de l’équipe dirigeante, fermé des filiales dans une dizaine de pays et gelé les dividendes  Twitter
A la tête du groupe allemand depuis juillet 2015, le Britannique John Cryan dresse un état des lieux sans concession de l’organisation, fustigeant les bonus trop élevés de certains banquiers et qualifiant les systèmes informatiques de « minables ». Il a changé la quasi-totalité de l’équipe dirigeante, fermé des filiales dans une dizaine de pays et gelé les dividendes jusqu’à nouvel ordre.

Le « nettoyeur à sang froid », comme le surnomme la presse outre-Rhin, a également entrepris une douloureuse restructuration. Avec son réseau pléthorique d’agences sur le territoire allemand, dégageant des marges faibles, la banque de détail n’est pas épargnée. D’ici à la fin de la décennie, 9 000 postes seront supprimés, sur les 100 000 que compte le groupe. « John Cryan est parvenu à conclure un accord avec les syndicats allemands pour restructurer la banque de détail », souligne Richard Barnes, analyste crédit chez Standard & Poor’s en charge du dossier Deutsche Bank. « La politique de Cryan va totalement dans le bon sens. Mais il faudra attendre fin 2017 pour commencer à en voir les effets : le chantier est énorme », juge, quant à lui, David Benamou, un expert du secteur.

Plan de sauvetage
Si certains se sont hasardés à comparer Deutsche Bank à Lehman Brothers, cette banque d’affaires américaine dont la chute avait précipité la crise financière de 2008, le parallèle est très exagéré. Depuis 2007, la situation financière du groupe allemand s’est améliorée. Ses réserves en liquidités ont triplé et on est loin de la faillite. « Deutsche Bank peut se servir au guichet de la Banque centrale européenne, alors que Lehman Brothers n’avait pas accès à la Fed, ajoute Jean-Edouard Colliard, professeur de finance à HEC. Par ailleurs, les régulateurs ont instauré des ratios de liquidité beaucoup plus stricts qu’en 2008, qui sont censés éviter les faillites. » A 11,1 %, le ratio de capital de Deutsche Bank dépasse les exigences des autorités.

Un bémol cependant : les grandes banques européennes utilisent leur modèle interne, c’est-à-dire des méthodes maison pour calculer leur exposition au risque, tandis qu’aux Etats-Unis, c’est la méthode « standard », définie par le régulateur qui prévaut. D’où un soupçon pesant sur les banques européennes, et sur la Deutsche Bank en particulier : elles seraient en fait sous-capitalisées en cas de nouvelle crise systémique.

Des rumeurs ont évoqué la préparation d’un plan de sauvetage par le gouvernement d’Angela Merkel avec l’argent du contribuable Twitter
Par ailleurs, une augmentation de capital pourrait devenir nécessaire si le montant de l’amende américaine, qui fait actuellement l’objet de tractations intenses, était confirmé. Dans les conditions actuelles, une émission d’actions classique paraît compliquée. Les règles européennes prévoient certes la possibilité de mettre à contribution les créanciers d’une banque en difficulté, mais cette option est hautement improbable : c’est tout le système bancaire européen qui en pâtirait. Des rumeurs relayées par l’hebdomadaire Die Zeit ont évoqué la préparation d’un plan de sauvetage par le gouvernement d’Angela Merkel avec l’argent du contribuable. Berlin a formellement démenti et à l’approche des élections fédérales de 2017, deux Allemands sur trois sont opposés à une aide de l’Etat à Deutsche Bank.

Le Qatar, actionnaire depuis 2014, a déjà profité du prix bas de l’action pour monter à 10 % du capital à l’été 2015. Il pourrait aller plus loin. A moins que… Selon le quotidien Handelsblatt, plusieurs industriels allemands auraient évoqué la possibilité d’injecter plusieurs milliards d’euros dans la banque. Le come-back de la Deutschland AG. Un retour aux sources, en quelque sorte.`,
 author: 'THOMAS LESTAVEL',
 date: '2016-12-14',
 img: 'http://www.alternatives-economiques.fr/sites/default/files/public/styles/169-xlarge/public/field/image/rea_245243_136.jpg?itok=QhK3o4Sx',
 tags: ['économie', 'Allemagne', 'finance'],
}, {
 title: 'Le Hip-Hop en France : naissance et évolution en 7 photos, avec Thomas Blondeau',
 content: `Depuis les rassemblements des B-Boys au Trocadéro et les premiers concerts du Globo jusqu’aux succès populaires d’IAM, Booba ou des membres de la Sexion d’Assaut, le Hip-hop français a traversé trente ans. Durant cette période, le rap a réussi, petit à petit, à se frayer une place de choix dans les classements musicaux populaires jusqu’à devenir le genre le plus écouté en France (cf. classement Spotify 2016).

C’est cette histoire que Thomas Blondeau, spécialiste de rap, ancien rédacteur en chef des magazines spécialisés R.E.R et Radikal (et B-Boy en activité) a décidé de raconter à travers son ouvrage Hip-Hop : une Histoire française. Pour Clique, il partage et commente sept photos tirées de son livre pour tenter de retracer cette épopée.
http://www.clique.tv/wp-content/uploads/2017/01/Hip004.jpg
 1. Coincé entre les stations Stalingrad et La Chapelle, ce terrain vague découvert en 1986 par des graffeurs est semblable à des dizaines de terrains de la région parisienne où se réunissaient alors les adeptes de la culture Hip-hop naissante. Aujourd’hui détruit, il reste l’objet d’une mythologie trompeuse : ce n’est pas ici que se réunissaient les premiers B-Boys français, mais plutôt ici qu’ils se sont retrouvés, une fois l’euphorie médiatique des années 1980 retombée. On avait affaire à des radicaux, et c’est ici qu’ils ont fini par inventer, à l’écart de médias devenus moqueurs, ce qu’on appelle aujourd’hui le Hip-hop français.
 http://www.clique.tv/wp-content/uploads/2017/01/Hip001-1301x2000.jpg
 2. On ne célèbrera jamais assez Daniel Bigeault aka Dee Nasty. Compositeur, producteur, DJ, multi-instrumentiste dont les notes résonnaient alors jusque chez les Rita Mitsouko, il est le Grandmaster des après-midi du terrain vague de la Chapelle, le représentant local de l’Universal Zulu Nation et l’un des premiers à se décarcasser pour que cette culture qu’il a découverte aux Etats-Unis soit diffusée en France – à travers ses émissions de radio, sur RDH ou Radio Nova. En 1984, armé d’un sampler, de deux platines et d’une table de mixage rudimentaire dont le crossfader était bricolé par un ami, il enregistre « Paname City Rappin’ », le premier album de rap français.
 http://www.clique.tv/wp-content/uploads/2017/01/Hip-hop-graff.jpg
 3. Lorsque le terrain vague de la Chapelle est détruit, graffeurs et tagueurs se dispersent dans la ville, descendent dans les galeries du métro, retournent les palissades, franchissent les murs et repeignent la ville, son mobilier et ses transports en commun. Colorz, illustre représentant du crew V.E.P. (Vandales En Puissance) termine ici un whole-car, soit une rame de métro repeinte du sol au plafond. Suite au carton de la station Louvre-Rivoli, opéré en 1991 par trois graffeurs, la RATP et les pouvoirs publics prennent conscience de l’ampleur du phénomène et y portent un coup d’arrêt, tandis que la justice prononce pour la première fois des peines de prison à l’encontre des responsables.
 http://www.clique.tv/wp-content/uploads/2017/01/Akhenaton-.jpg
 4. Alors que le hip-hop français cartonne sur les ondes, Akhenaton (IAM), se moque de l’industrie du disque en campant, dans le morceau « J’ai pas de face » (1995), le personnage de Gamani, un directeur artistique véreux qui surfe sur les modes et transforme le rap en un ersatz de variété commerciale, moquant au passage boys bands et starlettes en plastique. Si le thème est récurrent dans le rap américain comme français, la période est particulièrement bien choisie…
 http://www.clique.tv/wp-content/uploads/2017/01/Secteur-A.jpg
 5. Les propos que Benjamin Chulvanij, alors directeur artistique chez EMI, tient dans mon livre résument à eux seuls cette photo de Stomy Bugsy, Passi et Doc Gynéco dans un grand hôtel parisien en 1998 : « Un type comme Stomy ne voulait pas être simplement une star dans son quartier, il voulait être une star, tout court. En tant que directeur artistique, je voulais donc que ces artistes donnent leurs interviews dans les mêmes endroits que n’importe quelle star du rock ou de la variété. Je louais alors pour eux les salons de l’Hotel Costes où Placebo et consorts donnaient à la même époque leurs interviews».
 http://www.clique.tv/wp-content/uploads/2017/01/Hip-hop-Break--e1484557235313.jpg
 6. Le Hip-hop en France, c’est aussi la danse. Mounir fait partie d’une nouvelle génération de B-Boys qui ont réinventé le breakdance à l’aube des années 2000. Avec son crew Vagabonds comme en solo, il a remporté des championnats aussi prestigieux que les Notorious IBE, Chelles Battle Pro ou Battle Of The Year, jusqu’à ravir, en 2012, le titre de champion du Red Bull BC One – le championnat du monde de breakdance en solo. Clarté du mouvement, précision du geste, il rejoue à l’été 2016 le battle qui a opposé, quinze ans plus tôt, son crew Vagabonds au Wanted Posse en finale du Battle Of The Year. Un combat légendaire qui allait marquer l’ascension des B-Boys français sur la scène mondiale.
 http://www.clique.tv/wp-content/uploads/2017/01/SCH-1-e1484752732423.jpg
 7. Année 2015. Catogan, jeans slim et méchante gouaille sudiste, tout est nouveau chez SCH – comme chez une poignée de ses compères qui changent le game au même moment. Théâtre urbain aux mœurs âpres et aux manières fortes, SCH c’est du Zola dans les cités d’Aubagne, familles recomposées, abandons et vie de rue à l’appui – Maheu avec un Uzi, tristesse en bandoulière, outillé comme à Medellin. C’est la vie de merde vue sous un autre angle, tirant derrière elle des sacs de dissensions internes – qui échappent bien souvent à son auteur. Et c’est brillant.
 http://www.clique.tv/wp-content/uploads/2017/01/Hip-Hop.jpg

L’excellent livre Hip-Hop : une Histoire française de Thomas Blondeau (éditions Tana) est disponible partout. 191 pages, des textes passionnants, des centaines de photos (dont certaines très rares) : nous vous le recommandons chaudement.`,
 author: 'Mouloud Achour',
 date: '2017-01-19',
 img: 'https://pbs.twimg.com/profile_images/674268992131997696/NNbdiGbk.jpg',
 tags: ['musique', 'Hip-hop', 'Rap', 'Livre', 'Rétrospective'],
}, {
 title: 'CES 2017 : La French Tech, 2ème délégation mondiale de startups dans l’Eureka Park',
 content: `Dans quelques jours s’ouvre le Consumer Electronic Show de Las Vegas, le grand rendez-vous annuel mondial de l’électronique grand public, qui fête cette année ses 50 ans.

Le CES est un temps fort pour les startups de la French Tech. Il s’est imposé comme le salon mondial BtoB aujourd’hui incontournable pour toutes les entreprises et startups qui veulent lancer leurs produits, pénétrer le marché américain, rencontrer des distributeurs et investisseurs du monde entier, se faire repérer par les medias internationaux…

Cette année encore, un rassemblement des startups françaises exposantes au CES est organisé à Paris avant le départ. La soirée a lieu le 14 décembre sur invitation des startups exclusivement.

LA FRENCH TECH, DEUXIÈME DÉLÉGATION MONDIALE DANS L’EUREKA PARK, L’ESPACE DÉDIÉ AUX STARTUPS.

Cette année, la France représentera la 3ème présence mondiale au CES avec 275 entreprises et structures exposantes, après les Etats-Unis avec 1713 entreprises et la Chine 1307 entreprises.

Parmi ces entreprises françaises exposantes, la grande majorité sont des startups.
233 ont été recensées, dont 178 rien que dans l’Eureka Park, l’espace dédié aux startups. Elles représentent dès lors la deuxième délégation mondiale de l'Eureka Park avec 32% des startups (Juste derrière les Etats-Unis -203 startups- et loin devant Israël, la Corée du sud ou encore la Chine).

Pour mémoire, les startups françaises au CES étaient au nombre de 66 en 2015, 128 en 2016 et donc 178 en 2017.

Au cœur de ce rassemblement de masse : l'Internet des objets, considéré par de nombreux analystes comme « la prochaine révolution industrielle ». En France, l’IOT devrait enregistrer un chiffre d'affaires de 15,2 milliards d'euros en 2020, selon l'Institut Montaigne et le cabinet de conseil américain A.T. Kearney.

POURQUOI UNE TELLE CROISSANCE DE LA PRÉSENCE FRANÇAISE AU CES ?

La French Tech de l’Internet des objets s’impose depuis 3 ans au CES International de Las Vegas et confirme sa place parmi les leaders mondiaux, avec des startups et scale-ups emblématiques comme Sigfox, Qowisio, Netatmo, Parrot, Devialet, Withings (racheté cette année par Nokia), Visiomed  ou des émergentes très prometteuses comme CybelAngel, Famoco, Giroptic, Awox, ou encore SevenHugs.

La qualité des ingénieurs et designers français, un tissu industriel performant pour la sous-traitance de la production électronique et logicielle ou encore les expertises reconnues en analyse de données et en intelligence artificielle sont les arguments avancés pour expliquer cette dynamique puissante du secteur de l’Internet des Objets en France.

La créativité des startups françaises a d’ailleurs été largement récompensée par des CES Innovation Awards 2017 à l’occasion du CES Unveiled (d’autres gardent le suspense jusqu’à Las Vegas).

Découvrez la liste complète des startups de la présence française au CES 2017 en téléchargement.

Par ailleurs, les grands groupes français plébiscitent  la vitalité des startups de la French Tech  dans ce secteur et s’engagent avec elles pour innover : La Poste (avec son Programme French IoT),  Engie (investisseur dans SigFox notamment), Legrand (investisseur dans Netatmo).
Les grands distributeurs français se sont également engagés depuis 2015 dans la promotion des «  Objets connectés de la French Tech » en les référençant dans leurs rayons : Auchan, Boulanger, Carrefour, Groupe Casino, Darty, Fnac, Leclerc, Leroy Merlin, Lick, Orange, Système U ou encore VentePrivée.

#APPEL : AIDEZ-NOUS À RECENSER LES STARTUPS FRANÇAISES PRÉSENTES AU CES 2017 !

Cette année encore nous recensons l’ensemble des entreprises françaises présentes au CES, qu’elles soient exposantes ou visiteurs, grand groupe ou startups, venues en délégation ou par leurs propres moyens, exposantes dans ou hors de l’Eureka Park.

Découvrez les 90 startups déjà recensées sur notre plateforme !

Aidez-nous à compléter ce recensement pour atteindre les 233 startups exposantes. Partagez ce lien autour de vous ! L’inscription prend environ 7 minutes.

Votre société sera valorisée dans les actions de communication et notamment dans les relations presse françaises et internationales. Ce recensement vous permettra :

>>> d’apparaitre sur cette plateforme regroupant l’ensemble des startups françaises exposantes au CES. Elle sera visible par les journalistes, les parties prenantes et le grand public, avant et pendant le CES 2017, et accessible notamment sur le stand officiel de La French Tech dans l’Eureka Park ;

>>> d’être intégré à l’ensemble des communications relatives à la présence de la French Tech au CES 2017 (Relations presse, relations publiques), au niveau national et international, vers les médias et influenceurs français et internationaux;

>>> d’être tenu informé du programme de l’ensemble de la présence française au CES 2017.



La mission French Tech, l’équipe qui pilote l’initiative French Tech au Ministère de l’Economie et des Finances, organise depuis 3 ans un recensement des startups françaises présentes au CES en partenariat et en coordination avec l’un de ses partenaires fondateurs Business France.
`,
 author: 'Inconnu',
 date: '2017-01-02',
 img: 'http://www.lafrenchtech.com/sites/default/files/images/la_french_tech_night_ces-5.jpg',
 tags: ['Tech', 'International', 'Start-up'],
}, {
 title: 'Cadeaux de Noël : le sexisme dès le plus jeune âge ?',
 content: `Jeudi midi, au Mac Donald’s de Saint Michel, une mère d’une quarantaine d’années s’insurge. L’équipière MacDonald’s s’est trompée de jouet dans le Happy Meal de sa fille. Au lieu du jouet fille Hello Kitty, elle a eu le jouet garçon Pokémon. Scandale. « Ah non ça ne va pas du tout, Pokémon c’est pour les garçons, pas pour les filles ! Hello Kitty ça oui c’est pour les filles ». Et voilà comment créer le sexisme dès le plus jeune âge.

Ce petit fait a priori innocent résonne avec un autre fait. Sur Twitter, un père a reçu une ribambelle d’insultes à l’égard de son fils insinuant sa future homosexualité, après avoir partagé le fait que son fils demandait une poupée à Noël. Nous sommes dans une société qui a peur de voir grandir ses enfants dans une forme de perversion. Une fille doit se comporter comme une fille, un garçon comme un garçon. L’inverse choque et dérange. Tout se joue dès l’enfance puisque c’est à ce moment-là que se forge l’adulte de demain. Noël et ses jouets sont l’occasion d’étudier le chemin balisé de notre genre. Une poupée pour une fille, un camion de pompier pour un garçon, voilà comment ne pas arriver à la perversion de l’enfant. Vraiment ? Revenons sur l’inégalité des genres dans les cadeaux de Noël avec une classe de CP dans le XIIe arrondissement de Paris qui tend à redonner espoir.

Une histoire des couleurs : le rose pour les filles, le bleu pour les garçons

Le classique « rose/bleu » est la matérialisation du clivage filles/garçons. Il est intéressant de faire une histoire des couleurs pour montrer que l’assimilation du rose aux filles et du bleu aux garçons est récente. Au milieu du XIXème siècle, le rose était assimilé aux garçons et le bleu aux filles. Le bleu étant la couleur de la Vierge Marie, on y associait plus les filles pour la grâce et la pureté alors que le rose était une couleur affirmée, forte et donc plus pour les garçons.
Dans les années 50, le rose devient un marqueur de féminité mais les garçons le portait toujours. Dans les années 70, le rose et le bleu ne dominaient pas le marché de la couleur. Aux États-Unis, on portait davantage le rouge et le jaune. Le rose et le bleu ont pris le sens qu’on leur donne aujourd’hui dans les années 90 avec l’échographie. Très simplement, après avoir pris connaissance du sexe de leur enfant avec l’échographie, les futurs parents ont commencé à se précipiter pour acheter le matériel pour bébé en « version fille » ou en « version garçon ». La génération 90 est la génération du clivage rose/bleu, qui a vu les pages fille et les pages garçon du catalogue de Noël bien différenciées s’interdisant peut-être quelques souhaits sur leur liste de Noël.

Le repli sur soi pour les filles et le dépassement de soi pour les garçons : une vision irréelle de la société dans les catalogues de jouets

Dans un colloque international sur l’enfance de 2010, le sociologue Mona Zegaï est intervenu sur les mouvances et les permanences des catégories de genre dans les catalogues de jouets. Elle montre que la différenciation très nette garçon/fille dans les catalogues de jouets est assez récente et date du début des années 1990. La mise en place de la catégorie « fille » et de la catégorie « garçon » permet une certaine concision pour classer les jeux. Les garçons se voient attribuer ce qui est du domaine du « véhicule » (camion, garage, circuit) alors que les filles ce qui relève de la puériculture (jeux ménagers, poupées).

Ces catalogues donnent plus de consistance au message portant sur la division sexuée du monde. Ils ne perpétuent pas seulement les inégalités des genres que l’on peut trouver dans le monde réel, ils les exacerbent. Contrairement à ce que veulent montrer les catalogues de jouets, le travail masculin ne se limite pas au bricolage et les femmes ne sont pas que des fées du logis et sont loin d’être absentes de toute vie active. Lorsqu’elles sont représentées dans une activité professionnelle, celle-ci est nécessairement sexuée (les femmes sont mannequins ou caissières). Même chose pour les hommes, qui sont policiers ou pompiers. La réalité sociale est bien plus nuancée.

Les photographies dans les catalogues de jouets « genrent » les jouets. Ayant monté un cabinet d’études sur les questions d’égalité entre les genres (Trezego), Astrid Leray  a étudié 10 catalogues de jouets parus en 2013. Les filles ont une position passive dans les catalogues. Pour illustrer la catégorie « peluche », 51 photographies sur 60 représentent une petite fille tenant la peluche. Par ailleurs, 73% des photographies liées au dessin représentent des filles. Les garçons dans les catalogues sont davantage représentés en mouvement. 92% des armes dans les catalogues sont détenues par des garçons. Finalement, nous retrouvons les filles dans des jeux de « repli », qui touchent à la sphère privée, la coopération et le câlin alors que les garçons sont dans le dépassement de soi.

Contenir le sexisme chez les plus jeunes

Le problème est que l’identité sexuée se construit dès le plus jeune âge. Entre 5 et 7 ans, « la valeur accordée aux stéréotypes de sexe est à son apogée chez les enfants » expliquait en 2005 le psychopédagogue Nicolas Murcier lors d’un atelier organisé à Bruxelles. Par divers procédés d’imitation des parents, les enfants acquièrent des valeurs, des pratiques, des attitudes.
Lorsque les publicités, Internet ou les parents eux-mêmes orientent les enfants vers « ce que la société attend d’eux », c’est-à-dire de se comporter comme une fille en voulant jouer à la poupée et à la dinette ou comme un garçon en commandant des hélicoptères télécommandés et des déguisements de super-héros, on dégrade cet idéal de la société où filles et garçons se verraient proposer les mêmes opportunités.

Dans un rapport du Sénat sorti en 2013, il est souligné que les stéréotypes dans les jeux sont plus forts que ce que les enfants peuvent voir dans la réalité. Par exemple, il y a une hyper sexualisation des petites filles (maquillage, poupées un peu « sexy »…). Elles sont portées à plaire et les jouets qui leur sont destinées tendent à montrer que c’est une propension naturelle. La commercialisation de stéréotypes aboutit à une forme de laideur. Les jouets genrées sont « kitsch » et portent une vision dégradante en tendant vers l’exagération : les héros sont nécessairement bodybuildés tandis que les Barbies sont hyper féminisées. Le rapport a été remis à la délégation sénatoriale aux droits des femmes et à l’égalité des chances entre les hommes et les femmes présidée par Chantal Jouanno. Ce rapport contient certaines recommandations comme la mise en place d’une charte pour pousser les fabricants à être les initiateurs de l’égalité, la vigilance accrue du CSA quant aux publicités afin d’éviter tout message sexiste et des séances de prévention à l’école pour sensibiliser aux valeurs d’égalité.

Les classes de CP à l’ère d’aujourd’hui

J’ai voulu constater l’inégalité des genres dans les cadeaux de Noël en rencontrant une classe de CP. Mais contre toute attente, les élèves ont rejetés tous les clichés si convenus de l’inégalité des genres dans les cadeaux de Noël, ce qui redonne espoir en la génération suivante. Direction une petite école privée du XIIème arrondissement de Paris où tous les milieux se côtoient. Dans cette classe de CP de 25 élèves âgés de 6 ans, avec autant de filles que de garçons, nous parlons de la liste de cadeaux faite au Père Noël. La mode cette année est aux cartes Pokémon et au Rubik’s cube qui note un retour vintage en force des années 80.

Lorsque je leur demande ce qu’ils ont pu mettre sur leur liste de Noël, les jouets restent genrés : déguisement de Blanche-Neige, poupée Reine des Neiges, des dodo câlin (couverture en forme d’animal) ou encore des tables à langer ou de la nourriture pour poupées chez les filles. Chez les garçons, nous retrouvons le classique train électrique ou l’hélicoptère télécommandé, les cartes Pokémon, les jeux de football ou d’espion et les pistolets en plastique. Néanmoins, cet entretien nous livre quelques surprises notamment dans les souhaits des filles. Certaines demandent des cartes Pokémon, une montre Pokémon, des figurines Mario ou encore un train électrique. Est-ce l’amorce d’une enfance évoluant, comme notre société avec l’ouverture du mariage homosexuel, vers une libération des genres ? Lorsque je leur demande quelle est leur couleur préférée, seulement deux filles me disent que c’est le rose. Le bleu l’emporte largement avec 11 mains levées dont 5 de filles. Le rouge a quelques faveurs et le violet aussi, ce dernier est la couleur préférée d’une fille et d’un garçon.

En leur montrant des jouets non-sexués, c’est-à-dire sans marqueur garçon/fille apparent, généralement en bois et très simple, ils ne semblent pas déterminés par leur sexe. 60% de la classe pensent que la dinette est aussi bien pour les filles que pour les garçons. 40% de la classe pensent que la poussette est destinée aussi bien aux filles qu’aux garçons. En discutant avec eux, ils semblent détachés de tout a priori filles/garçons, ils pensent que tous les jeux s’adressent à tout le monde. Le classique de la poupée étonne : la moitié de la classe pense qu’elles ne sont destinées uniquement aux filles mais 8 autres élèves pensent que c’est autant pour les filles que pour les garçons.

Le monde du jouet est-il en mutation au moment même où le foyer progresse ? Les jouets commandés à Noël sont en grande partie des jouets dits « d’imitation » qui visent à imiter l’environnement : dinette, cuisinière, épicerie, caisse enregistreuse, table de bricolage… Maintenant que les tâches ménagères sont plus équitablement partagées dans le foyer et que les pères militent pour le congé parental d’éducation, les modèles ne sont plus les mêmes et les listes de Noël évoluent parallèlement à notre société. Le clivage fille/garçon ne semble plus aussi vif que dans les années 90. La phrase de Simone de Beauvoir n’est peut-être plus aussi vrai aujourd’hui. Elle disait : « on ne naît pas femme on le devient ». Cependant, aujourd’hui si tel est le cas, pourquoi le deviendrions-nous ?`,
 author: 'Chloé Berry',
 date: '2016-12-23',
 img: 'https://sorb-on.fr/wp-content/uploads/2016/12/blur-1867322_640.jpg',
 tags: ['cadeaux', 'genre', 'Noël','sexisme','société'],
}, {
 title: 'Sauver la mer Morte avec la mer Rouge : le projet fou de la Jordanie et d’Israël',
 content: `La mer Morte cristallise tous les problèmes géopolitiques du Moyen Orient : une rareté de la ressource en eau, des besoins importants pour l’agriculture et l’eau potable, une manne touristique fragile et une écologie qui passe bien souvent au dernier rang des préoccupations.

Ainsi la Mer Morte est en passe de… Mourir. Son assèchement n’est qu’une question d’années tant les prélèvements se font importants dans sa principale source d’alimentation, le fleuve Jourdain. Pour empêcher ce funeste destin, la Jordanie et Israël ont décidé de réagir en annonçant la construction d’un gigantesque pipeline de 180 Km de long reliant la Mer Rouge à la Mer Morte. Ce canal souterrain sera accompagné par la plus grande usine de désalinisation d’eau de mer. L’objectif ? Ni plus ni moins que résoudre la pénurie d’eau potable de la région et sauver le trésor culturel qu’est la mer Morte.

La mer Morte, un enjeu avant tout économique

Si Israël et la Jordanie ont décidé de mettre de côté leurs rancœurs c’est bien parce que l’enjeu économique est primordial pour la région. L’eau du Jourdain, qui alimente la mer morte, est prélevée à 95% par les pays riverains pour l’agriculture tandis que le tourisme représente une part toujours plus importante de l’économie du Royaume de Jordanie. A 429 mètres au-dessous du niveau des mers, la mer la plus basse du monde est en train de s’assécher, en menaçant le tourisme balnéaire et patrimonial.

Le site traditionnel du baptême du Christ dans le Jourdain, les grottes de Qumran où furent découverts les manuscrits de la mer Morte, et l’attraction de la mer en elle même drainent des millions de touristes tous les ans pour les pays riverains, dont les eaux très salées sont réputées en balnéothérapie. Son exceptionnel taux de salinité, 247 grammes par litre contre seulement 9 pour la méditerranée en fait une attraction recherchée… Mais en danger.
L’activité d’extraction de minéraux par évaporation est aussi responsable de l’assèchement de la mer Morte. Chaque année, 600.000 tonnes de sel y sont extraites et sont utilisées dans l’industrie agroalimentaire ou cosmétique.

La Jordanie est a présent le second pays le plus pauvre en eau. Entre une mauvaise gestion de la ressource, due à une fraude importante au compteur ainsi qu’un prix du m3 insuffisant, le royaume hachémite a désespérément besoin de cette ressource vitale pour sa population, qui augmente brutalement depuis quatre ans sous l’afflux d’un million et demi de réfugié en provenance de Syrie.

Il y a donc urgence : si la mer disparaît comme il est prévu dans 30 ans, c’est la population et toute l’économie de la région qui va en pâtir, ce qui renforcera les tensions géopolitiques déjà existantes.

Le “canal de la paix” pour sauver la Mer Morte

C’est une idée vieille de 50 ans qui commence enfin à se concrétiser : le 28 Novembre la Jordanie a annoncé avoir choisi les cinq consortiums internationaux (France, Japon, Chine, Singapour, Canada) regroupant près de 20 entreprises pour lancer les travaux à partir de 2018.

canal de la paix pour sauver la mer Morte
Cette première phase prévoit la construction d’un pipeline de 180 Km pour relier la mer Rouge à la mer Morte, ainsi qu’une usine de dessalement pour apporter de l’eau douce à toute la région. Financé en partie par la Banque Mondiale et des pays donateurs, le projet a véritablement été lancé par les accords de coopération de 2013 entre Israël, la Jordanie et la Cisjordanie occupée, ce qui lui vaut le surnom de “canal de la paix”.

Les chiffres sont pharaoniques : l’usine doit pouvoir traiter à terme 85 millions de m3 par an, ce qui en ferait la plus importante au monde, tandis que 300 millions de m3 d’eau seraient déversés dans le pipeline à partir du captage en mer Rouge.
Cette première phase est estimée à un milliard de dollars, tandis que la totalité du projet se monterait à terme à 10 milliards de dollars !

Cette gigantesque entreprise est censée sauver la mer Morte de sa lente agonie, qui voit son niveau baisser d’un mètre par an depuis 1970. Mais les ONG locales s’inquiètent de l’impact du déversement brutal d’une telle quantité d’eau de mer, qui pourrait entraîner le développement d’algues rouges et de cristaux de gypse. Dans son étude de faisabilité, la banque Mondiale a elle même reconnu un risque écologique, toutefois maîtrisable.

Carte de la mer Morte 2016
De même, l’usine de dessalement ne satisfait pas les associations qui pointent son manque d’ambition et ses immenses besoins d’énergie. Friends of the Earth Middle East (FOEME) dénonce également un prix de l’eau inabordable pour les populations locales : pour ces ONG une réforme en profondeur du système de distribution d’eau est nécessaire pour faire des économies.

Sauver la mer Morte permettra aussi à Israël d’y trouver son compte en évitant une renégociation des accords de partage des eaux du Jourdain, qui sont très favorables à son agriculture. Le canal devrait permettre aux agriculteurs locaux de pouvoir puiser dans le fleuve sans s’inquiéter d’impacter la mer Morte.

Le “canal de la mer Rouge à la mer Morte”, son nom officiel, devra donc permettre de stabiliser la région en évitant une de ces fameuses “guerre de l’eau” que l’on nous promet régulièrement. Sécurisation de l’approvisionnement en eau potable, sauvetage des activités touristiques et économiques de la mer Morte, pacification des relations dans cette région trop souvent explosive : à première vue, que des avantages. Mais vu l’ampleur pharaonique des travaux envisagés et leur côté totalement novateur, ce brillant succès diplomatique pourrait très bien se transformer en désastre écologique si seuls les intérêts économiques continuent de primer.`,
 author: 'Niels de Girval',
 date: '2017-01-17',
 img: 'http://e-rse.net/wp-content/uploads/2016/12/sauver-mer-morte-mer-rouge-710x434.jpg',
 tags: ['monde', 'environnement', 'RSE', 'Moyen Orient', 'Développement durable', 'Biodiversité'],
}, {
 title: 'Si c\'était possible, voudrions-nous vraiment être immortels ?',
 content: `Vivre pour toujours, dans le corps de son choix, sans jamais vieillir, voilà une promesse du transhumanisme qui paraît attrayante. Si nous pouvions devenir des cyborgs, quelles seraient les conséquences pour nous-même et notre monde ? Un futur utopique ou la fin de notre humanité ?
 RRécemment, lors d’un mariage, j’ai interrogé des amis sur le concept d’immortalité. « Imaginez que dès demain vous puissiez numériser votre cerveau pour vivre pour toujours en tant qu’hybride homme-machine. Le feriez-vous ? », ais-je demandé à un couple de surdiplômés, parents de deux petites filles. L’époux, un docteur en médecine de 42 ans, a répondu oui sans aucune hésitation. Il a expliqué que ses recherches actuelles ne porteront leur fruit que dans quelques centaines d’années, et il voudrait voir ce qu’il en adviendra. « J’aimerai aussi voir à quoi ressemblera le monde d’ici 10 000 ans », a-t-il précisé. Son épouse, une docteure en histoire de l’art de 39 ans, a également été sans équivoque : « Hors de question », a-t-elle répondu, « la mort fait partie de la vie. Je veux savoir ce que ça fait de mourir. »

Je me suis demandé si la décision de sa femme pourrait conduire le mari de à se remettre question, mais pour des raisons diplomatiques, j’ai décidé de ne pas poursuivre la discussion. Quoi qu’il en soit, cette réflexion dépasse le stade des simples banalités échangées en soirée. À en croire certains futurologues, nous finirons tôt ou tard par devoir répondre à ce genre de questions. Selon eux, nous nous dirigeons tout droit vers un monde post-biologique dans lequel la mort appartient au passé – ou est tout du moins sous contrôle.

La version la plus concrète de ce futur transcendant est celle imaginée par le chercheur et essayiste Ray Kurzweil. Dans son best-seller paru en 2005, Humanité 2.0 (The Singularity Is Near), Kurzweil prédit que « l’intelligence artificielle englobera bientôt toutes les connaissances et compétences humaines. » La technologie de numérisation du cerveau à l’échelle nanométrique permettra à terme « le transfert graduel de notre personnalité et de nos compétences vers une partie synthétique de notre intelligence ». Pendant ce temps, au sein de notre organisme, des millions de nanorobots « détruiront les pathogènes, corrigeront les mutations de notre ADN, élimineront les toxines et réaliseront bien d’autres tâches pour améliorer notre condition physique. Résultat : nous serons capables de vivre indéfiniment sans vieillir ». Ces nanorobots créeront « une réalité virtuelle à partir de notre système nerveux ». Nous vivrons de plus en plus dans le monde virtuel qui deviendra impossible à distinguer de l’univers que nous appelons « réalité ».

D’après les progrès effectués dans le domaine de la génétique, de la nanotechnologie et de la robotique, Ray Kurzweil estime la date de la « singularité » – le moment auquel l’intelligence synthétique dépassera l’intelligence humaine à tel point qu’elle produira une transformation profonde de nos capacités – à 2045. De nos jours, les avancées récentes dans le domaine algorithmique de l’apprentissage profond n’a fait qu’encourager certains chantres de la singularité à continuer de croire en cette date.

Toutefois, la plupart des scientifiques pensent que notre destin de cyborg est encore bien loin. Sebastian Seung, professeur à l’Institut de neurosciences de Princeton, pense que la numérisation du cerveau ne sera peut-être jamais possible. Le cerveau est constitué de 100 milliards de neurones, connectés entre eux par des synapses. L’ensemble de ces connexions forment le connectome qui, selon certains neurologues, serait la clé de notre identité. Même avec les progrès technologiques prévus par Ray Kurzweil, cela représente une quantité gigantesque de connections à cartographier et à numériser. De plus, le connectome pourrait n’être que le début : les neurones peuvent aussi interagir en dehors des synapses, et de telles « connexions extra-synaptiques » pourraient s’avérer essentielles pour le fonctionnement du cerveau. Si c’est le cas, comme Sebastian Seung le soutient dans son livre Connectome : How the Brain’s Wiring Makes Us Who We Are, paru en 2012, la numérisation d’un cerveau devrait non seulement inclure chaque connexion et chaque neurone, mais aussi chaque atome qui le constitue. La puissance de calcul nécessaire « est complètement hors de portée à moins que nos descendants éloignés survivent assez longtemps pour la développer, à une échelle de temps galactique ».

Quoi qu’il en soit, la possibilité d’un tel futur, qu’il soit lointain ou peu plausible, soulève une inquiétude suffisamment importante pour que les philosophes en débattent sérieusement. Même si notre technologie échoue à accomplir la vision de Ray Kurzweil, l’augmentation de notre conscience et de notre corps pourrait nous rapprocher en partie de cet avenir., ce qui pose la question de savoir ce qui fait de nous des êtres humains.

J’ai demandé à David Chalmers, philosophe et co-directeur du Center for Mind, Brain and Consciousness à l’Université de New York, qui a écrit sur le moyen de numériser notre cerveau pour préserver notre identité, s’il pense qu’il aura l’opportunité d’accéder à la vie éternelle. Chalmers, âgé de 50 ans, a répondu que non. Mais pour lui, « il est certain que ces problématiques vont devenir réelles à un moment ou à un autre d’ici les cent prochaines années ».

Pour Ronald Sandler, expert en éthique de l’environnement et président du département de philosophie et de religion de l’Université de Northeastern à Boston, parler de notre futur de potentiel cyborg « soulève beaucoup de questions. Se projeter dans un avenir lointain permet de mieux se questionner sur notre futur proche ».

S’il y a la moindre possibilité que nous puissions un jour choisir entre la mort et l’immortalité en tant que cyborg, il est peut-être plus sage d’y réfléchir dès aujourd’hui. En écartant le problème de la faisabilité, il est important de prendre le temps de se poser des questions plus fondamentales : est-il souhaitable de devenir des cyborgs ? Si mon cerveau et ma conscience étaient téléchargés dans un cyborg, qui serais-je ? Aimerais-je toujours ma famille et mes amis ? Et eux, m’aimeraient-ils encore ? Au final, serais-je toujours un être humain ?

L’une des problématiques abordées par les philosophes est la façon dont nous nous traitons les uns les autres. La « règle d’or », ou éthique de réciprocité, « traite les autres comme tu voudrais être traité » existerait-elle encore dans un monde post-humain ? Il y a quelques années, dans une publication intitulée Transhumanisme, dignité humaine et statut moral, Ronald Sandler soutenait que les humains « augmentés » maintiendraient une certaine obligation morale envers les humains « normaux ». « Même si vous êtes amélioré, vous ne pouvez pas cesser de vous préoccuper d’autrui » explique-t-il. Ce qui semble dur à contredire – mais aussi plus difficile encore à croire.

D’autres philosophes s’intéressent à « l’amélioration morale » - l’usage de moyens médicaux ou biomédicaux pour améliorer nos principes moraux. Si nous sommes amenés à disposer d’une grande intelligence et d’un grand pouvoir, nous devrions nous assurer que le diable ne soit pas aux commandes. D’après les philosophes Julian Savulescu et Ingmar Persson, nos connaissances scientifiques « commencent à nous permettre d’affecter directement les bases biologiques ou physiologiques de la motivation que ce soit par l’usage de substances pharmaceutiques, de modifications génétiques, ou des dispositifs qui affectent le cerveau et les processus d’apprentissage. Nous pourrions utiliser ces techniques pour surpasser les imperfections morales et psychologiques qui mettent en péril l’espèce humaine. »

Dans un article paru en mai 2016 dans le Washington Post, intitulé Nous utiliserons bientôt la science pour améliorer la morale des humains, James Hughes, vice-doyen de l’Université du Massachusetts, à Boston, plaide en faveur d’une amélioration morale, qui doit être volontaire plutôt que coercitive. « Avec l’aide de la science, nous pourrons découvrir notre propre voie technologique vers le bonheur et la vertu », explique ce bioéthicien, qui dirige l’Institut de l’éthique et des technologies émergentes, un groupe de réflexion transhumaniste (Ancien moine bouddhiste âgé de 55 ans, James Hughes aimerait, pour sa part, rester en vie suffisamment longtemps pour atteindre l’illumination).

Se pose également la question de la manière dont nous devrions traiter la planète. Quelle qu’en soit la forme, vivre éternellement changerait notre rapport à l’autre mais aussi au reste du monde. Cela nous rendrait-il plus ou moins sensible à l’environnement ? La nature y gagnerait-elle quelque chose, ou serait-ce le contraire ?

Ronald Sandler m’a fait remarquer que la singularité décrit un état final. Pour y parvenir, il faudrait vivre une révolution technologique de grande envergure et « rien ne change notre rapport à la nature plus rapidement et profondément que la technologie ». Lorsque nous arriverons à numériser la conscience humaine au point de pouvoir aller et venir entre le monde réel et le monde virtuel, nous aurons déjà inventé tout le reste. Pour Ronald Sandler, « lorsque la singularité se produira, notre relation avec l’environnement aura déjà radicalement changé ».

Bien que nous aimerions croire le contraire, dans notre état actuel de simple mortel, nous dépendons énormément de la nature, autant que nous y sommes vulnérables. Mais dans ce monde futur, ces dépendances pourraient changer. Si nous n’avions pas la nécessité de respirer par nos poumons, pourquoi nous préoccuperions-nous de la pollution de l’air ? Si nous n’avions plus besoin de cultiver notre nourriture, nous serions déconnectés de la terre qui nous entoure.

De la même manière, dans un monde où la réalité n’est pas distinguable du virtuel, nous pourrions autant bénéficier de la nature créée numériquement que de l’authentique « grand air ». Notre rapport à l’environnement réel serait altéré et il ne s’agirait plus de quelque chose de physique ou de sensoriel. Ce décalage pourrait avoir un impact profond sur notre cerveau, et peut-être même sur sa version artificielle. Les recherches montrent qu’interagir avec la nature nous affecte en profondeur – et pour le meilleur. Un lien avec la nature, même à un niveau inconscient, serait fondamental à l’être humain.

Si notre dépendance à la nature disparait et si notre capacité à communier avec elle diminue, « la base nécessaire à notre sensibilité environnementale va progressivement décliner, entraînant avec elle notre sens de la responsabilité », explique Ronald Sandler. Notre capacité à résoudre les problèmes environnementaux – comme par exemple avec l’ingénierie du climat – dépassera tout ce que l’on peut imaginer aujourd’hui. Mais ressentirons-nous toujours l’importance de la nature ? Si oui, les écosystèmes s’en porteront mieux. Sinon, les espèces et les écosystèmes desquels elles dépendent seront en danger.

Notre relation avec l’environnement est aussi une question de temps. À l’échelle des temps géologiques, l’extinction de masse que nous connaissons actuellement pourrait être sans importance. Mais à l’échelle d’une vie humaine, elle a des conséquences. « Comment l’extension de notre espérance de vie remettrait-elle en perspective la façon dont nous gérons l’environnement non-humain ? » se questionne Ronald Sandler. « L’échelle de temps doit être prise en compte pour répondre raisonnablement à ces problématiques ». Serons-nous plus sensibles à l’environnement parce que nous l’habiterons plus longtemps ? Ou nous sentirons-nous moins concernés en adoptant un point de vue temporel plus large ? Pour Ronald Sandler : «  il est quasiment impossible d’imaginer comment nous penserons, mais nous pouvons être sûr que la perspective sera très différente. »

Parlez assez longtemps de cela à des experts du sujet, et vous vous retrouverez à avoir des conversations en apparence ordinaires sur des sujets absurdes. Au détour d’une conversation, James Hughes expliquait ainsi que « s’il existait quelque chose comme une thérapie génique inspirée des X-Men, grâce à laquelle on pourrait tirer des lasers avec les yeux ou contrôler les esprits, les gens qui voudraient ces pouvoirs devraient d’abord suivre des entraînements spéciaux et obtenir une sorte de permis ».

« Évoquez-vous cet exemple pour prouver quelque chose ou croyez-vous vraiment que cela va finir par se produire ? », ais-je alors demandé. « Nous essayons de ne pas effrayer les nouveaux venus avec tout ce que pourrait changer le transhumanisme. Mais une fois le choc passé, nous pourrions parler du jour où nous ne serons plus qu’un amas de nanorobots », m’a-t-il répondu de façon ambigüe.

De quoi nous inquièterons-nous, quand nous ne serons plus qu’un amas de nanorobots ? L’angoisse, après tout, est l’un des critères qui nous définit comme humains. L’immortalité rend-elle l’angoisse obsolète ? Si je n’avais plus besoin de me soucier de ma santé et de ce que je vais devenir quand je serais trop vieille, serais-je toujours moi-même ? Ou ne serais-je plus qu’un robot serein et sur-satisfait ? Qu’en serait-il de mes rêves ? Perdrais-je mon ambition ? Si je vivais pour toujours, je pourrais bien attendre le siècle suivant pour écrire mon roman, n’est-ce pas ? Serais-je toujours moi-même ? Pour David Chalmers, « cette question philosophique va finir par devenir concrète et urgente à régler ».

Intérieurement, il me paraît peu plausible que je reste moi-même si mon cerveau était numérisé – même si je le faisais neurone par neurone, comme David Chalmers l’a préconisé, en restant consciente lors du processus, devenant progressivement artificielle à 1, 5, 10 puis 100 %. C’est comme dans le casse-tête du navire de Thésée, dont les planches sont remplacées une par une par des nouvelles. Est-ce encore le même navire au bout du compte ? Si ce n’est pas le cas, à quel moment cesse-t-il de l’être ?

Pour James Hughes, « l’un des problèmes majeurs, c’est que vous vivrez si longtemps et connaîtrez tellement de changements que vous arriverez à un point auquel il n’y a plus de raison de vivre davantage. Suis-je la même personne que lorsque j’avais cinq ans ? Si je vis 5 000 ans de plus, serai-je le même que maintenant ? Dans le futur, nous serons capables de partager nos souvenirs, donc l’importance de l’identité et de la continuité personnelle s’érodera ». Voilà qui est dérangeant.

Malgré son aspect utopique, la singularité véhicule avec elle une nuance de fatalisme : la seule option qui s’offre à nous consiste à choisir entre fusionner avec les machines ou disparaître, voire pire. Et si je ne veux pas devenir un cyborg ? Ray Kurzweil dirait peut-être que c’est mon cerveau biologique, défectueux et limité qui m’empêche de voir le véritable potentiel de cet avenir. Il dirait que les options s’offrant à moi – le corps de mon choix, une réalité virtuelle, une créativité sans limite et la possibilité de coloniser l’espace – me mèneront à percevoir mon actuelle existence biologique comme comique et triviale. Et de toute façon, qu’y-a-il de plus fataliste qu’une mort certaine ?

Quoi qu’il en soit, j’aime beaucoup être humaine. J’aime savoir que je suis fondamentalement constituée de la même chose que toute vie sur Terre. Je suis même attachée à ma fragilité d’humaine, en quelques sortes. Je préfère être chaleureuse et câline plutôt qu’être dure et indestructible comme le sont certains super-robots dans les films d’action. J’aime le sang chaud qui coule dans mes veines et je ne suis pas sûre de vouloir le remplacer par des nanorobots.

Certains éthiciens soutiennent que notre bonheur dépend du fait que nos vies sont fugaces, et que nous sommes des êtres vulnérables et interdépendants. Comment trouverions-nous un sens à la vie dans un futur d’hommes-machines ?

Pour Ray Kurzweil, « l’essence même de l’être humain ne réside pas en ses limites, mais en sa capacité à les dépasser ». C’est un point de vue attrayant. La mort a toujours été l’une de ces limites, alors peut-être que s’en affranchir fait profondément de nous des humains ? Mais une fois la mort transcendée, je ne suis pas convaincue que notre humanité persiste. La mort, en elle-même, ne nous définit pas – bien que toute chose vivante finisse par mourir – mais notre conscience et notre compréhension de la mort, et notre quête pour donner du sens au temps qui nous est donné, font très certainement partie intégrante de l’esprit humain.`,
 author: 'Hillary Rosner',
 date: '2017-01-17',
 img: 'http://www.pourlascience.fr/e_img/boutique/transhumanisme_sciam0916.jpg',
 tags: ['philosophie', 'science', 'société', 'Tech'],
}];

export default articles;
