import React from 'react';

const prisme4 = [{
  title: 'La «smart city» n’est pas si «smart» que ça',
  img: 'http://www.slate.fr/sites/default/files/styles/1090x500/public/lyon-confluence.jpg',
  author: 'Franck Gintrand, David Nguyen',
  category: 'Point negatif',
  source: 'Slate',
  content:
    <article>
      <p>À l’origine de la smart city, une idée noble: favoriser une qualité de vie élevée dans le cadre d’un développement optimal des ressources grâce à une gestion efficiente de la data et des réseaux. Mais le premier bilan de la plus smart des cities françaises qu’est Lyon a de quoi étonner... et décevoir.</p>
      <p>Qui l’eût cru? Selon une étude réalisée en janvier 2014 par le Parlement européen, 90% des villes européennes de plus de 500.000 habitants et 43% des villes de 100 à 200.000 habitants seraient des «smart cities». Voilà qui, dans un contexte pour le moins morose, donnerait presque du baume au cœur si, derrière ces chiffres ne se cachaient de fortes disparités. Ainsi que le précise le rapport, en matière de «smart city», toutes les villes n’ont pas atteint le même niveau de «maturité».</p>
      <p>Au vu de ce méga test de QI urbain, l’Europe ne compterait en tout et pour tout que six surdouées présentant la caractéristique d’être dotées d'une «politique ou d'une stratégie de ville intelligente»: Amsterdam, Barcelone, Copenhague, Helsinki, Manchester et Vienne. Sur un échantillon constitué des 468 plus grandes villes européennes analysées, pas de quoi pavoiser. Ni pour l’Europe, ni a fortiori pour la France.</p>
      <p>Heureusement, Lyon, classée dixième, sauve l’honneur. Cette place honorable ne doit rien au hasard. Ces dernières années, la capitale des Gaules a mis les bouchées doubles. Contrairement à de nombreux politiques qui ont attendu les municipales de 2014 pour faire de la smart city un thème de campagne, Gérard Collomb a pressenti l’intérêt du sujet dès 2010 en signant un accord avec le NEDO, l’équivalent nippon de l’Ademe (Agence de l’environnement et de la maîtrise de l’énergie), pour faire du quartier Confluence une «smart community» avec des bâtiments à énergie positive, des compteurs intelligents et des voitures électriques en auto-partage. Depuis, les projets se sont multipliés sous le label «Grand Lyon Métropole Intelligente» dans les domaines de la mobilité, de l’énergie et du numérique. Un engagement tous azimut qui s’est rapidement révélé payant en matière d’image. Outre le fait d’être classée numéro 10 sur 468 villes par le Parlement européen, Lyon arrive en tête du premier palmarès des smart cities françaises, devant Lille et Nantes.</p>
      <p>Appellation fourre-tout</p>
      <p>Mais, au fait, que faut-il entendre par «smart city»? C’est tout le problème. Ou du moins, une partie du problème. Pour le Parlement européen, une smart city est «une ville qui cherche à résoudre les problèmes publics grâce à des solutions basées sur les TIC sur la base de partenariats d’initiative municipale et mobilisant de multiples parties prenantes». Selon Rudolf Giffinger, universitaire viennois et théoricien référent en matière de smart city, cette définition se décline dans six domaines clé: l’économie, la mobilité, l’environnement, le mode de vie, l’administration et les habitants. Après tout, pourquoi pas. Sinon que cette définition n’a rien d’officielle, ni de suffisamment évidente pour s’imposer d’elle-même.</p>
      <p>Bien sûr, le palmarès des smart cities françaises hisse, lui aussi, la mobilité au rang de priorité. Mais, côté environnement, le classement se veut plus précis en retenant les «télécoms», l’eau, l’énergie et la gestion des déchets. Quant aux questions de gouvernance, plutôt que de parler d’économie, d’administration et d’habitants intelligents, le palmarès préfère évoquer la «vision de la municipalité de la ville durable» et la «qualité de vie».</p>
      <p>À la limite peu importe. Car, de son côté, Lyon revendique sa propre définition de la smart city. Ici pas question de six ou huit domaines clé mais de «quatre idées essentielles»: les enjeux environnementaux et énergétiques, le fonctionnement en réseaux, le passage de la propriété à l’usage, sans oublier, bien entendu, les nouvelles technologies.</p>
      <p>Lyon n’est pas un cas isolé. On pourrait égrener à l’infini les variations conceptuelles de la smart city. C’est bien simple: chaque collectivité y va de sa définition au point que l’observateur désireux de s’y retrouver s’enlise un peu plus à mesure qu’il prend connaissance d’une documentation pléthorique où se mêlent divergences universitaires mais aussi considérations politiques et, bien entendu, arrières pensées commerciales.</p>
      <h3>Logique d’empilement sans cohérence d’ensemble</h3>
      <p>Même sentiment de confusion lorsqu’on cherche à savoir précisément ce que recouvre une «stratégie smart city» à travers l’exemple de Lyon. Il faut dire que, là encore, rien n’est conçu pour faciliter une approche critique. Ni la succession de chiffres qui donne le sentiment d’un immense foisonnement avec ses «quatre thématiques principales» mais aussi ses «quarante expérimentations en cours», ses «cent partenaires privés et publics» ou encore ses «vingt millions de données trafic récoltées par jour». Ni la longue litanie d’appellations déposées: «vélo’v», «sunmoov’», «bluefly», «smart electric lyon», «optimod’», «tuba», «opticities», «watt&moi» ou encore «mug». Ni, surtout, le caractère extrêmement vague des objectifs puisque la smart city à la lyonnaise se propose de «concilier développement des secteurs de demain et développement durable en bonne intelligence».</p>
      <p>Hormis l’invocation de «nouveaux modèles» et la volonté affichée de «nouvelles solutions», on ne saura rien des synergies recherchées entre les «quatre thématiques principales» qui justifieraient l’intégration de «quarante expérimentations en cours» au sein d’un même programme. Ni de la façon intelligente qui voudrait, par exemple, que l’on croise des données d’origine différentes et dans des secteurs différents pour résoudre de façon innovante des problèmes bien identifiés. Ni, bien entendu, des problèmes concrets que Lyon se propose de résoudre.</p>
      <p>Qu’il semble loin le temps où Bill Clinton, utilisant pour la première fois le terme de smart city, appelait le géant du numérique Cisco à «développer des plans de décongestion des villes, à commencer par San Francisco, Séoul et Amsterdam». L’enjeu fixé par le président américain était sans doute démesuré et en grande partie utopique mais au moins l’ambition avait un sens et du souffle. Elle contenait en elle la possibilité d’une stratégie et d’une évaluation. En comparaison, la smart city lyonnaise semble bien pauvre. Aucune logique d’ensemble sinon une accumulation de moyens reliés par un usage commun des NTIC. Est-ce suffisant pour en faire un axe de développement territorial visionnaire? Ce serait oublier qu’améliorer le fonctionnement d’une ville grâce à la technologie n’a rien de très nouveau et qu’une plateforme de suivi digital du trafic diffère finalement assez peu de l’installation du premier feu rouge aux États-Unis en 1914.</p>
      <h3>Partenaires très privilégiés</h3>
      <p>Au-delà de la question de sa cohérence, la smart city interroge également sur les rapports qu’elle institue entre acteurs privés et publics. À Lyon, un accord cadre lie depuis 2011 l’agglomération à EDF, désigné comme prestataire privilégié pour mener des expérimentations en matière de smart grids. Une approche qui permet à l’heureux élu de faire partiellement cofinancer ses recherches et surtout d’écarter la concurrence à laquelle s’est pourtant ouverte le marché français. Déjà, l’accord avec le NEDO prévoyait une exclusivité similaire pour l’entreprise Toshiba.</p>
      <p>Bien sûr, pour se défendre de toute attitude monopolistique, les prestataires retenus mettent en avant les inévitables partenariats qu’impliquent les projets smart city. Mais force est de constater qu’il s’agit principalement de s’allier avec des acteurs non concurrents, ou le cas échéant, avec des entreprises de taille moindre.</p>
      <p>L’exemple d’EDF est de ce point de vue parfaitement éclairant. Parmi les partenaires associés au géant français, on trouve des acteurs de la filière de l’industrie électrique, de l’équipement de la maison, du BTP et des télécoms (Orange et SFR). Mais au nom de quel principe ce tour de table n’inclut-il pas les autres fournisseurs d’énergie? Quelle logique justifie la position monopolistique d’un acteur privé en phase de recherche dans le cadre d’un programme placé sous l’égide de l’Ademe et de la seconde ville française? Une chose est sûre: ce n’est généralement pas la stratégie retenue pour faire émerger les solutions les plus pertinentes au meilleur coût.</p>
      <p>La première possibilité, la plus fréquente, consiste pour les acteurs publics à miser sur la concurrence et à retenir la solution la plus performante, conformément à l’esprit du marché public. La seconde consiste à s’engager aux côtés des entreprises mais en exigeant, en contrepartie, une mise en commun des efforts de recherche, ouverte et égalitaire entre acteurs concurrents et de taille différente. Aucune de ces stratégies n’a été retenue à Lyon. Dans le cas de la smart city, il ne s’agit ni de mise en concurrence, ni de mutualisation mais d’un pilotage pour le moins curieux.</p>
      <h3>Coûts exorbitants et résultats discutables</h3>
      <p>Mais après tout, doit-on s’offusquer d’une définition floue et d’un pilotage incertain si la smart city apporte un gain incontestable pour les citoyens-utilisateurs? L’essentiel n’est-il pas d’obtenir des résultats? Oui, très certainement. Pour autant, force est de constater que la montagne risque bien d’accoucher d’une souris.</p>
      <p>Le projet phare lyonnais de fluidification du trafic «Optimod’», lancé en 2012 et bénéficiant de 7 millions d’euros de financement, vient seulement de franchir la première étape de collecte des données en temps réel. C’est en soi une performance technique. Mais on peut légitimement craindre que les utilisateurs lyonnais auront déjà opté pour d’autres solutions lorsque les premières applications concrètes d’Optimod’ verront le jour. Comment par exemple faire face à une solution de gestion de trafic collaborative comme Waze, rachetée pour 1 milliard de dollars par Google, et forte de plusieurs millions d’utilisateurs en France?</p>
      <p>Au-delà de Lyon, l’expérience Linky à l’échelle nationale vient souligner la relativité des résultats obtenus à ce jour en matière de smart city. L’installation de 35 millions d’exemplaires du compteur intelligent d’ErDF pour 4,5 milliards d’euros, s’est avérée être un échec. Alors qu’on promettait des économies d’énergie significatives, les premières études ont révélées que, «pour 90 % des consommateurs, l’arrivée de Linky n’a rien modifié dans leurs pratiques».</p>
      <p>On découvrirait ainsi un peu tard que, sans appropriation par les usagers, les technologies ne changent pas le réel. Bien sûr, il se trouvera toujours des chiffres un tant soit peu significatifs pour justifier en dernière instance la pertinence du modèle de la smart city. Mais en quoi ce modèle aura-t-il vraiment joué un rôle dans les avancées opérées par les opérateurs privés? On peut en réalité d’ores et déjà se poser la question.</p>
      <h3>Que de la com’?</h3>
      <p>Finalement la smart city, à Lyon ou ailleurs, pourrait bien être ce que beaucoup pressentent depuis l’origine: un concept marketing à succès. De la même manière qu’il y a eu un engouement des collectivités territoriales pour l’«Agenda 21», aujourd’hui en perte de vitesse, l’hystérie smart city pourrait bien rapidement retomber. Un tour rapide sur Google Trends permet de suivre la trajectoire descendante du sujet «Agenda 21» depuis 2005, c'est-à-dire l’année même où le concept de smart city a pris son envol. Corrélation ne veut pas dire causalité, mais on peut malgré tout parier que, lorsque toutes les villes auront revendiqué une politique smart city, plus aucune ne le sera particulièrement et que, les médias étant repus, de moins en moins d’élus s’en réclameront. Certainement au profit d’un nouvel étendard.</p>
      <p>Cela veut-il dire que l’engouement pour la smart city relève du phénomène hors sol et quelque peu disproportionné? Une chose est certaine: à bien regarder l'exemple de Lyon, la question mérite d'être posée tant l'analyse des faits donne le sentiment d'une façade dissimulant quelque chose qui ressemblerait à de la simple communication autour d’innovations technologiques plus ou moins inévitables.</p>
      <p>Les synergies entre les différents domaines d'action? On les perçoit difficilement. Les partenariats entre les entreprises pour trouver des solutions innovantes? Ils ressemblent plutôt à une façon pour Lyon de acorder un avantage concurrentiel à EDF ou Toshiba sur de futurs marchés. Les résultats concrets? Là encore, ils sont sujets à caution ou, faute d’objectifs quantifiables, terriblement flous.</p>
      <p>À défaut d'intelligence, la smart city de Lyon reste une intention et un label autodécerné de modernité. Un peu juste quand même. En tout cas, à l'heure où Paris s'apprête à investir énormément d'argent et où d'autres grandes agglomérations ne demandent qu'à suivre l'exemple de Lyon, il serait temps d'être plus critique et plus exigeant sur le contenu exact de la smart city. Les enjeux de la mobilité et de l'environnement le justifient pleinement.</p>
    </article>
  }, {
    title: 'Mais d\'où vient cette idée bizarre de « ville intelligente » ?',
    img: 'http://static.latribune.fr/full_width/436323/songdo.jpg',
    author: 'Francis Pisani',
    category: 'Histoire',
    source: 'Tribune',
    content:
      <article>
        <p>L'expression de "villes intelligentes" - les "smart cities" en anglais - fait désormais partie du vocabulaire courant des nouvelles théories de la vie urbaine. Retour sur la généalogie du concept.</p>
        <p>C'est grâce à Bill Clinton que les Occidentaux se sont mis à parler de « smart cities ». Mais les Coréens se sont lancés plus tôt sur une piste semblable avec un nom qui n'a pas pris. Les autres ont suivi le mouvement.</p>
        <p>L'idée semble être sortie d'un défi lancé en 2005 par l'ancien président des États Unis à John Chambers, président de Cisco, le fabriquant d'équipements pour réseaux digitaux : pourquoi ne pas utiliser ses fascinants outils technologiques pour rendre les villes plus durables.</p>
        <p>L'entreprise lança une recherche sur le sujet (avec un budget de 25 millions de dollars) dont elle décida de commercialiser les résultats en 2010. En 2008, IBM se joint à la ruée vers l'or (les villes intelligentes sont le plus gros marché TIC des années à venir) avec son initiative « Smarter Cities».</p>
        <h3>Convergence des deux grandes révolutions</h3>
        <p>Clinton avait vu la convergence de deux des grandes r-évolutions de ce début de siècle : l'urbanisation massive et l'explosion des technologies de l'information... qui n'avait pas échappé aux acteurs sur le terrain. Lors du deuxième Sommet mondial des Autorités Locales sur la Société de l'Information qui s'est tenu en 2005 à Bilbao, les participants ont « défini une stratégie commune » d'accès de leurs territoires aux TIC. C'était la première fois que ce genre de réunion organisée par l'Onu et traditionnellement réservée aux États, était ouverte aux autorités locales, aux entreprises privées et à la société civile.</p>
        <p>La tendance s'est accélérée en 2008, explique le chercheur Anthony Townsend dans son excellent livre Smart Cities: Big Data, Civic Hackers, and the Quest for a New Utopia. C'est l'année de trois points d'inflexion déterminants pour le monde entier, trois dépassements : la population rurale par l'urbaine ; le nombre des lignes fixes (DSL, câble ou fibre optique) par les utilisateurs de lignes à haut débit sur mobile ; le nombre d'humains en ligne par les objets connectés.</p>
        <p>Mais on a tort de ne regarder que l'Occident. Dés 2003, la Corée du Sud a commencé à mentionner dans ses documents officiels l'existence d'une stratégie reposant sur la notion d'informatique omniprésente (ubiquitous computing). Ça allait du u-network à la u-society, du réseau omniprésent à la société connectée, pour déboucher sur une u-Korea. Le « u » représente l'ubiquité des TIC et la volonté d'en tirer parti au maximum pour développer le pays et faire évoluer la société. C'est donc sous le nom de u-cities que les villes intelligentes ont officiellement été inscrites au programme du gouvernement en 2006.</p>
        <p><i>« En 2004, les Coréens avaient accès à l'internet de n'importe où, à n'importe quel moment, avec n'importe quel appareil », m'a rappelé Jong-Sung Hwang, responsable du big data pour la ville de Séoul. « Mais nous avons démarré trop tôt et, ni la technologie ni le marché n'étaient assez développés pour soutenir notre vision et notre effort.»</i></p>
        <p>En 2005, la Corée a lancé un plan de 12 u-cities dont le seul succès, selon Hwang, est Songdo, ville entièrement nouvelle dont il attribue la réussite (relative) au fait qu'elle a pu « intégrer l'infrastructure » posée avant les immeubles. Mais il reconnaît qu'elle « est restée figée à ce niveau qu'elle doit maintenant dépasser » pour accéder à la dimension sociale. Un retard d'autant plus notable que le concept a été lancé dès les années 1990, m'a expliqué Scott Summers, vice président de Gale International, l'entreprise américaine chargée de mener à bien le projet sur lequel elle a commencé à travailler dès 2001.</p>
        <h3>La Chine s'y est mise sérieusement à partir de 2010</h3>
        <p>Notons enfin que la Chine s'est lancée sérieusement dans l'aventure des villes intelligentes à partir de l'exposition universelle de Shanghai en 2010.</p>
        <p>En Europe, sensible à l'idée et active dans ce domaine, l'impulsion est donnée depuis un certain temps déjà par des villes comme Amsterdam ou Barcelone. Mais la communauté s'y est mise sérieusement en 2010.</p>
        <p>Dernière venue, l'Inde, qui a des problèmes énormes d'urbanisation, entend mettre les bouchées doubles. Dès son arrivée au pouvoir en mai 2014, Narendra Modi a promis de construire 100 villes intelligentes au plus vite et d'allouer un budget d'un milliard d'euros à cet effet</p>
      </article>
    }, {
      title: 'Mais d\'où vient cette idée bizarre de « ville intelligente » ?',
      img: 'https://www.lesechos-events.fr/media/_uploads_versions/events/Gab_Bandeau-1200x420-SMART_CITIES_5IhuGZU_panoralarger.jpg',
      author: 'Agathe Mercante',
      category: 'Politique',
      source: 'Echos',
      content:
        <article>
          <p>A mesure que les agglomérations s'équipent, les porteurs des projets de villes intelligentes recherchent l'expertise des habitants. Les citoyens adhèrent d'autant plus à cette démocratie participative que les outils se multiplient.</p>
          <p>Des bornes de stationnement connectées, les horaires des transports en commun indiqués en temps réel, la consommation d'énergie optimisée ou encore un accès au Wi-Fi illimité dans la rue... Les domaines qui composent la ville intelligente et connectée sont légion. Mais cette course à l'équipement numérique connaît un tournant, comme le pointe une étude du Nesta, publiée au mois de mars. Selon cette organisation britannique spécialisée dans l'innovation, un bon développement des smart cities doit passer par une meilleure implication de leurs habitants. En France, la ville intelligente continue de s'équiper en nouvelles technologies mais voit, en parallèle, l'émergence de nouveaux riverains : les smart citizens, qui s'investissent dans sa création. Réseaux sociaux, applications mobiles et pétitions en ligne sont désormais entrés dans les usages courants et rejoignent les assemblées de quartier et les associations dans l'expression de la volonté citoyenne. Ces nouvelles pratiques et équipements numériques sont une opportunité, pour les collectivités, de mieux communiquer sur leurs actions. A Nantes, l'agglomération a renforcé sa communication numérique en développant une application (Nantes dans ma poche) qui permet aux habitants de la métropole d'obtenir des informations sur les équipements municipaux, sur la politique menée, mais aussi d'interpeller les élus. « Plus qu'une simple information, les habitants attendent aujourd'hui d'être impliqués dans la politique de la ville ", estime Yves Mathieu, fondateur et directeur de l'agence Missions publiques, spécialisée dans les démarches participatives. « Il faut augmenter les interactions entre les citoyens et leurs élus », explique-t-il. Paris a mis à disposition des habitants plusieurs outils. La plate-forme numérique « Madame la maire, j'ai une idée " encourage, par exemple, les Parisiens à formuler des propositions, qui seront discutées lors d'assises sur ces thématiques. Une part du budget de la ville est également soumis à l'approbation des citadins.</p>
          <h3>Des équipements mieux adaptés</h3>
          <p>« Nous notons beaucoup plus de propositions que de critiques de la part des participants aux consultations ", explique Eric Hamelin, cofondateur de Carticipe, une plate-forme de cartographie participative en ligne. Récemment, cet outil a été utilisé afin de consulter les habitants de Grenoble-Alpes-Métropole dans le cadre du plan local d'urbanisme intercommunal. « Les habitants ont une vraie légitimité à donner leur avis sur la politique locale », explique-t-il. Les outils numériques ne font pourtant pas tout : « Il est indispensable d'avoir recours aux rencontres physiques », explique Yves Matthieu. « Nous n'avons pas eu beaucoup de retours sur notre application, mais lors d'enquêtes de terrain, les riverains ont été nombreux à s'exprimer », pointe Raphaël Cherrier, fondateur de Qucit, une application destinée à réaliser la concertation publique autour des travaux d'aménagement de la place de la Nation, à Paris. Plans locaux d'urbanisme, concertations publiques relatives à la mobilité en ville, organisation des rythmes scolaires, des crèches... Sur Internet ou de visu, les motifs de consultation sont nombreux et les informations émanant des citoyens précieuses. « L'intelligence de la smart city, elle vient de ses habitants », explique Valerie Issarny, chercheuse spécialiste du sujet à Institut national de recherche en informatique et en automatique (Inria). Et les élus locaux l'ont bien compris. Ces nouveaux modes de consultation citoyenne sont en effet partie intégrante du crowdsourcing, une utilisation des idées émises par les citoyens. Des données qui permettent le développement d'équipements mieux adaptés (mobilité, réseaux, énergies) mais modifient les rapports entre les élus et leurs administrés. « La démarche de démocratie participative demande une capacité à capter les envies de citoyens, en charge aux élus de tendre vers une plus grande transparence, il ne faut pas que ces consultations restent sans effet », prévient Mathieu Saujot, coordinateur du programme « fabrique urbaine » au sein de l'Institut du développement durable et des relations internationales (Iddri). Le jeu en vaut la chandelle : « La démocratie participative permet de réaliser des projets que les élus seuls n'auraient pas pu mener ", explique le chercheur.</p>
        </article>
    }, {
      title: 'Ces métiers que la smart city va inventer',
      img: 'https://www.lesechos-events.fr/media/_uploads_versions/events/Gab_Bandeau-1200x420-SMART_CITIES_5IhuGZU_panoralarger.jpg',
      author: 'Matthieu Deleneuville',
      category: 'Economie',
      source: 'JDN',
      content:
        <article>
          <p>IoT advisers, mobility designers, service planners… Autant de métiers qu'entreprises et communes vont devoir recruter pour gérer la mise en place des villes intelligentes.</p>
          <p>La smart city ne se fera ni en un jour, ni toute seule. Car si les technologies sont déjà matures, de nombreux talents doivent naître pour les faire éclore. L'enjeu est considérable pour les communes : "C'est là la question de l'empowerment : si vous voulez avoir une ville numérique maîtrisée, il faut que les citoyens qui habitent cette ville maîtrisent le numérique", confiait récemment au JDN Jean-Louis Missika, adjoint à la maire de Paris chargé de l'urbanisme.</p>
          <h3>Dans les mairies, des gestionnaires smart city…</h3>
          <p>Pour faire face à la nouvelle vague technologique, les villes auront d'abord besoin de gestionnaires de projets smart city : "Ces responsables des partenariats smart city devront être capables de dialoguer sur les nouvelles technologies avec les prestataires et de comprendre les choix technologiques", explique Christian Tordo, adjoint au maire de Nice délégué à l'économie à l'emploi et à l'industrie.</p>
          <p>"Travailler en interne sur la smart city est très coûteux car il faut prévoir les frais de maintenance et le renouvellement des équipements, qui évoluent en permanence. C'est pourquoi il nous faut un gestionnaire qui puisse savoir à qui s'adresser selon les projets, même si cela représente un changement culturel majeur pour les mairies, qui voulaient autrefois tout faire par elles-mêmes", poursuit l'élu.</p>
          <h3>… et des IoT advisers</h3>
          <p>Même constat du côté de Marseille, où l'on veut s'armer le mieux possible pour faire les bons choix face aux multiples solutions disponibles sur le marché : "Un IoT adviser (conseiller sur l'Internet des Objets, NDLR) pourrait nous être très utile. Il s'agirait d'un spécialiste des objets connectés au courant de toutes les solutions possibles et qui serait capable de créer de nouveaux usages dans la ville en prenant en compte la problématique du coût mais aussi de la qualité du service", explique Didier Parakian, adjoint au maire délégué à l'économie.</p>
          <h3>Dans les entreprises, des IoT designers…</h3>
          <p>Pour développer ces objets connectés, les entreprises devront elles aussi dénicher de nouveaux talents. A commencer par des IoT designers : "Il s'agirait d'un profil à la fois technicien et designer qui serait en mesure de connecter n'importe quel objet du quotidien pour en décupler l'utilité", imagine Alexandre Pelletier, responsable de l'innovation de l'entreprise indienne Tata Communications. </p>
          <p>Car selon lui, le design des capteurs destinés est primordial : "En Inde, les communes travaillent beaucoup sur la sécurité des femmes, qui est là-bas une problématique très importante. Il faut par exemple être en mesure d'imaginer un bijou à la fois discret et capable de contenir un capteur, une antenne et une batterie pour en faire un système d'alerte et de géolocalisation efficace."</p>
          <h3>… des techniciens et logisticiens IoT…</h3>
          <p>Et en ce qui concerne les capteurs intégrés aux équipements des smart cities, là encore, de nouvelles compétences seront requises : "Nous aurons besoin d'installateurs spécialisés dans l'IoT avec des connaissances techniques mais aussi une très bonne maîtrise de la logistique des objets connectés", affirme Pierre Bonzom, PDG d'ELA Innovation, spécialiste montpelliérain de la technologie de géolocalisation RFID.</p>
          <p>"Nous avons par exemple équipé les conteneurs du livreur DPD de puces permettant de les localiser précisément et en temps réel. Il y a là un réel enjeu car il faut être capable de déployer, puis de réparer si nécessaire, les 1 200 capteurs nécessaires sur des conteneurs répartis aux quatre coins de la France dans 62 agences et en perpétuel mouvement. Il y a donc un aspect prédictif : le technicien doit savoir où être et quand", poursuit-il.</p>
          <h3>… et des architectes IoT</h3>
          <p>L'entrepreneur imagine aussi un métier d'architecte réseau IoT : "Nos clients intégrateurs manquent de ce qui serait en quelque sorte un cartographe de l'objet connecté, qui sache déterminer où le poser pour le mettre en réseau avec les autres capteurs et assurer un maillage de toute la zone concernée. Il créerait, comme le font les opérateurs de téléphonie mobile pour le réseau cellulaire, des logiciels de prévision et de simulation de propagation des fréquences."</p>
          <p>"Cette fonction de déployeur de connectivité intègre à la fois du génie civil et des compétences électriques, qui n'existent pas combinées sur le marché. En ce moment on demande à des gens du génie civil de mettre cela en place alors que cela ne correspond pas à leurs compétences historiques", renchérit Mamy Ravelojaona, responsable marketing opérationnel pour le Pôle SI, Réseaux & Télécoms de l'entreprise de conseil française Alten.</p>
          <p>Il faut pouvoir toucher tous les citoyens mais aussi avoir un service concret à leur proposer : "Des développeurs de services data devront mettre en place des interfaces destinées à l'usager final pour le partage des données récoltées par les capteurs. Cela se fera en virtuel mais aussi en physique, avec la création d'écrans tactiles dans les abribus, par exemple", prévoit-il.</p>
          <h3>Pour les transports, des mobility designers…</h3>
          <p>Autre exigence qui s'imposera aux smart cities dans les années à venir : tirer le meilleur des voitures sans chauffeur.</p>
          <p>Philip Parsons est en charge du projet Audi Urban Future Initiative à Somerville, un partenariat entre le constructeur automobile allemand et la commune américaine qui prévoit notamment la construction de parkings automatisés et d'un trafic routier mieux maîtrisé grâce au véhicule autonome.</p>
          <p>Pour lui, ce nouveau mode de transport va profondément changer la manière d'aborder l'urbanisme : "Aujourd'hui, urbanistes et constructeurs automobiles travaillent chacun de leur côté. Demain, ils devront tout maîtriser et deviendront ce que l'on pourrait appeler des mobility designers, c'est-à-dire des spécialistes de la mobilité de demain. Et pour l'instant, les professionnels du secteur ne sont pas entraînés à cela."</p>
          <p>Concrètement, une fois totalement intégrée à la ville, la voiture sans chauffeur sera déployée en flottes qui nécessiteront, un peu à l'image de la gestion des vélos en libre-service dans certaines grandes villes, d'être maîtrisées : "Il faudra prévoir des managers de flottes mais aussi des contrôleurs de trafic, comme ce qui existe actuellement dans les aéroports, pour assurer la fluidité de la circulation et le bon approvisionnement en véhicules des parkings automatiques", explique Philip Parsons.</p>
          <h3>… et des service planners de véhicules autonomes</h3>
          <p>Une révolution qui s'apprête selon lui à tout chambouler jusqu'au au sein même des constructeurs automobiles : "La voiture ne sera plus un produit mais un service. Comme la musique sur les plateformes de streaming, la voiture se partagera, se louera ponctuellement, mais ne nous appartiendra plus. Mais ce n'est pas pour autant que le service ne devra plus être premium. Au contraire : Audi aura besoin de service planners capables de trouver et de déployer de nouvelles offres appliquées aux véhicules autonomes.</p>
          <h3>Dans le BTP, des coordinateurs BIM</h3>
          <p>Une onde de choc qui se propagera jusque dans le BTP, assure Marie-Françoise Guyonnaud, responsable pédagogique du MBA smart city et management des éco-quartiers à l'Institut Léonard de Vinci : "Les villes auront besoin de coordinateurs BIM (Building Information Modeling) qui géreront l'intégration des technologies à toutes les étapes de conception et de fabrication et qui vérifieront toutes les données intégrées dans la maquette pour assurer un partage optimal."</p>
          <h3>Pour la data, des juristes-techniciens</h3>
          <p>Des données, encore des données, toujours des données… Et autant de contrariétés juridiques qui s'annoncent : "Des juristes spécialisés dans la smart city devront s'occuper de toutes les questions sur la protection de la vie privée et de la propriété intellectuelle", affirme Sébastien Duchemin, directeur du conseil smart city chez Sopra Steria.</p>
          <p>"Chaque data a son propriétaire, privé ou public. Il faut donc des gestionnaires de données qui sont à la fois des juristes et des techniciens capables de comprendre la réglementation sur le partage des données", précise Mamy Ravelojaona.</p>
          <p>Ne serait-ce que pour expérimenter, de nombreuses compétences en droit seraient indispensables selon Sébastien Duchemin : "Le code des marchés publics n'est pas le meilleur outil pour conduire des projets innovants. Il y a notamment beaucoup d'innovations dans les montages financiers public – privé qui impliquent une maîtrise totale des réglementations autour de la smart city."</p>
          <p>Et même une fois le projet sorti de terre, un service après-vente juridique est à assurer : "Il y a aussi la problématique de la gestion du risque, comme sur le maintien à domicile des seniors, par exemple. Et si le système d'alerte en cas d'accident, aussi sophistiqué soit-il, ne fonctionne pas ? Il faut tout prévoir", poursuit le spécialiste de Sopra Steria.</p>
          <h3>Des smart ethnologues et sociologues …</h3>
          <p>La smart city n'a pas de frontière et les prestataires, s'ils ont l'ambition de s'exporter, vont devoir maîtriser certaines règles.</p>
          <p>Un sujet que maîtrise Alexandre Pelletier, qui travaille pour une filiale du groupe indien Tata : "Nous aurons besoin de sociologues, voire d'ethnologues de la smart city qui puissent savoir faire voyager les technologies selon la culture des pays. En Inde, par exemple, le stationnement est anarchique, contrairement aux grandes villes occidentales. Les solutions de l'Ouest seront alors difficilement transposables."</p>
          <p>Et les problématiques auxquelles doit répondre la smart city ne sont pas non plus les mêmes selon les pays : "De nombreux enfants disparaissent en Inde et il faut donc intégrer des outils de géolocalisation. Une question qui ne se pose pas en France, par exemple", raconte Alexandre Pelletier.</p>
          <h3>… et des évangélistes de la smart city</h3>
          <p>La technologie elle-même devra également être accessible à tous selon lui : "Dans les pays en voie de développement comme l'Inde, et des villes comme Mumbai avec peu d'infrastructures, la smart city posera un grand problème d'adaptation de la population. Il faudra une pédagogie, une sorte d'alphabétisation numérique. Et c'est le cas aussi pour les non-digital-natives dans les pays occidentaux, et notamment les plus âgés."</p>
        </article>
      }, {
        title: 'Smart Cities et Art Cities: 2 piliers du développement durable de la ville',
        img: 'http://images.atelier.net/sites/default/files/_illustrations/latelier-art-smartcity.jpg',
        author: 'Étienne Roché',
        category: 'Culture',
        source: 'Atelier',
        content:
          <article>
            <p>Comment réconcilier mobilité, plaisir et culture au coeur d’une ville, tout en aménageant habilement les éléments réels, inamovibles et les éléments virtuels, facteurs de globalisation?</p>
            <p>Ville et Culture sont deux histoires humaines intimement liées de longue date, dont les dernières décennies ont été le spectacle d’une vague d’uniformisation des centres urbains et de réorganisation du rôle des villes entre elles. Ce multi-centrisme, reflet d’une économie à présent globalisée est aussi le marqueur d’une mobilité extrême des centres de décision et de production bougeant à la faveur des conditions d’accueil du lieu. Pourtant, bien qu’une partie de la culture de la ville ait été diluée dans cette vague, une autre n’a pas bougé et ne bougera pas, ancrée dans la matérialité de ses murs et de ses rues, de ses traditions et de ses habitus. Les bâtiments, les toits, les musées, les parcs, les avenues, les spectacles, les festivals, les carnavals, les restaurants, les bibliothèques, les boites de nuit sont autant de témoignages inamovibles des patrimoines artistique, architectural, sociologique d’une ville et cernent les contours de sa culture et de son art de vivre que nous appellerons l’Art City.</p>
            <p>Dans le même temps, la globalisation des villes s’est accompagnée de celle de ses touristes. C’est de la rencontre de ces deux phénomènes, tourisme et culture globalisés, que naît une nouvelle tension : comment accueillir toujours plus de touristes, seule variable économique de grande ampleur mobilisable sur une courte période, et leur offrir dans le même temps la meilleure expérience d'une ville devenue avec le temps fortement urbanisée ? Comment faire cohabiter leurs allées et venues dans la ville avec les flux organiques de ses habitants ? Comment leur faire profiter au mieux de leur expérience avec toute la lenteur souhaitée mais avec toute la vitesse de la ville ? Comment donc conjuguer culture, mobilité et plaisir ? C’est tout le rôle de la Smart City que d’aider l’Art City : c’est tout d’abord lui apporter l’intelligence de se faire connaître sans céder à des TripAdvisor, Booking ou autres Expedia le monopole du choix des destinations; c’est aussi lui aider à accueillir dans les meilleures conditions ses visiteurs le temps d’un voyage, les inciter à revenir et voire in fine à s’y installer. De là, d’ailleurs, pourrait se renforcer l’attractivité des villes et des territoires pour les entreprises voulant y rejoindre une population ayant choisi son cadre de vie.</p>
            <h3>Conjuguer attractivité réelle et virtuelle</h3>
            <p>Smart City et Art City peuvent éventuellement à elles deux renverser la relation vis à vis du touriste. Actuellement réduite à un produit disponible sur les étagères des sites de voyages, elle peut être prescriptrice d’expérience réelle. Il faut considérer l’expérience de la ville pour un touriste sous l’angle de la ville qui se vit comme un spectacle, une ‘City as a venue’, et tirer le meilleur profit du numérique pour développer son attractivité, organiser et fluidifier les aspects logistiques, assurer le meilleur confort et la meilleure optimisation du temps (quitte à ne rien en faire !) afin d’offrir le plaisir de redécouvrir ce qu’on avait vu par écrans interposés. C’est également à la Ville de proposer à ses touristes ce qu’ils remporteront chez eux dans leur monde digital, à la manière d’une petite Tour Eiffel ou d’un petit morceau du mur de Berlin d’une autre époque. Ou inversement, de proposer ce qu'ils veulent laisser comme empreinte digitale dans ses murs tel l’exemple de la Ceinture de Lumière, association proposant à tous les amoureux de l’Opéra Garnier de financer la rénovation de ses cariatides et lampadaires extérieurs.</p>
            <p>Enfin, selon l’argument de l’urbaniste Français Paul Virilio, l’augmentation de la vitesse de déplacement entre centres urbains a conduit à une dévitalisation culturelle des espaces intermédiaires et donc des villes périphériques aux noeuds de ce super-réseau. Dans cette perspective, ces villes-phares peuvent servir de point de départ pour les territoires auxquels elles appartiennent. La Smart City n’est alors que la version réduite d’une Smart Region, fédérant les villes satellites dans une expérience culturelle toujours plus large d’une même Histoire, comme Avignon ou Nîmes. Dans le même esprit, le numérique peut relayer toujours plus fortement la volonté d’expansion culturelle de la Ville : consécration de nouveaux musées, construction de grands totems modifiant sa skyline (starchitectes et effet Bilbao), création de nouveaux événements culturels, volonté d’un nouveau style de ville (Berlin et l’Open City), autant de nouvelles pierres posées dans les destinations touristiques de chacun. Le numérique mondialise ainsi le territoire de la ville.</p>
          </article>
      }, {
        title: 'Maslow et Laborit, urbanistes de la Smart City',
        img: 'http://images.atelier.net/sites/default/files/_illustrations/latelier-Pyramide.jpg',
        author: 'Étienne Roché',
        category: 'Sociologie',
        source: 'Atelier',
        content:
          <article>
            <p>Après avoir envisagé la Smart City sous un angle culturel, il est aussi possible de l’aborder d’un point de vue sociologique.</p>
            <p>Si le phénomène d’urbanisation existe depuis des siècles et a pris autant d’ampleur, c’est qu’il répond toujours à des besoins profonds et lointains de la condition d’animal grégaire qu’est l’être humain. Il se trouve que la ville est un mode d’organisation sociétal particulièrement résilient; c’est aussi une mise en scène efficace du pouvoir dans l’espace. C’est enfin la force du collectif diffusée par et pour chacun. Mais qu’est-ce que chacun y trouve ?</p>
            <p>Le psychologue américain Abraham Maslow a exposé dans son fameux (mais décrié) modèle de la pyramide la hiérarchisation des besoins humains, qui ne peuvent être satisfaits que successivement. A l’instar des différents étages de cette pyramide, la ville permet d’aligner une solution à chacun de ces niveaux. Aux besoins physiologiques, elle fournit tous les flux de matières premières historiquement puisés dans son hinterland, par l’appui de réseaux énergétiques, d’eau voire de chaleur, toujours plus finement maillés. La ville procure bien évidemment le logement. Aux besoins de sécurité, la ville a su répondre par ses systèmes historiques de défense contre l’agresseur (ses murailles par exemple) ou par l’organisation d’une police dans la Cité. Aux besoins d’appartenance et d’amour est arrivée l’organisation de la vie en communauté, l’application de la justice et des lois sur son territoire, ou la définition de règlements internes (propreté). L’exercice du pouvoir, le travail et l’université ont quant à eux répondu aux besoins d’estime. Enfin, la quête de sens, les lieux de culte, l’histoire collective ont fait écho aux besoins d’accomplissement de soi.</p>
            <p>La ville peut donc être vue comme un moyen de répondre à tous les étages de cette pyramide, aux interférences près des imperfections historiques du lieu. Cet aspect a été largement mis en scène au cinéma, dans le néoréalisme italien par exemple, la ville apparaissant alors comme un aimant des populations rurales en quête d’une vie meilleure et plutôt bien servie jusqu’ici par la technologie.</p>
            <h3>Décentraliser ou centraliser les villes ?</h3>
            <p>Cependant cette attraction n’est pas sans limite. Des forces contraires apparaissent à partir d’une certaine échelle : l’étalement du tissu urbain causé par la construction de zones pavillonnaires (suburbia), de zones d’activités et de zones commerciales (boites à chaussures) est aussi la cause de l'explosion du trafic routier nécessaire pour couvrir cette surface ainsi que la pollution induite par ce dernier… Cet étirement jusqu’au déchirement fait aussi apparaître immanquablement des vides culturels difficiles à remplir, qui accentuent dans le même temps l’anonymisation de l’individu. Si la ville adresse bien la densité critique de chaque étage de la pyramide précédemment décrite, elle achoppe sur un point : celui de ne pas pouvoir faire croître à la même vitesse son patrimoine historique. Quid de la culture et de son histoire logées dans son centre historique ? La centralité n’est d’ailleurs pas qu’un enjeu culturel car elle impose par son influence radiale la valeur des territoires. Il y a un donc un intérêt individuel à habiter au centre pour atteindre le dernier étage de la pyramide. Mais appliqué au groupe, cela n’est pas possible. ll faut donc créer du sens à grande échelle pour régénérer la collectivité. Mais comment faire ? Faut-il reconstruire la ville autrement ? Faut-il densifier encore plus les centre-villes ? Faut-il légiférer sur les flux de personnes ? Cette tension apparait dans les premières mises en scène de déserts urbains des dernières décennies.</p>
            <h3>Choisir entre la fuite, l’agressivité ou l’inhibition</h3>
            <p>Face à ce trouble, différentes actions ont été menées de par le monde et les époques pour reconfigurer la ville. La grille d’analyse d’Henri Laborit peut nous aider. Elle catégorise notre comportement face à cette densification et contingent à chaque espèce animale. Citons d’abord la fuite ou l’Utopic City. Dans une fuite en avant, ce sont les projets de villes nouvelles faisant table rase du passé, les familistères ou les phalanstères d’antan, alimentées par de nouvelles utopies, animées de politiques emplies d'émotions et de lendemains dorés. Malheureusement, ces schémas n’ont pas d’histoire collective et puisent leur énergie dans la définition d'un éden qui n’a jamais existé. Ils n’ont donc que peu de recul pour envisager leur avenir. Henri Laborit évoque également l’agressivité ou la Coercitive City. Autrement dit, dans une tentative de contrôle des corps, de la circulation, il s'agit de figer l’histoire de la ville dans une photo et un âge jugés comme parfaits et mettant en scène une ville devenue chaotique et violente. Un exemple très médiatique de cet aspect est la démonstration de force du maire de Vilnius écrasant avec un char militaire le véhicule d'un contrevenant au stationnement.</p>
            <p>Enfin, est-il question de l’inhibition ou la Smart City : il ne faut pas changer ce qui existe et il faut continuer de supporter la densification des flux en les intégrant de mieux en mieux. C’est une approche réaliste considérant que le mouvement d’urbanisation est inéluctable et doit intégrer de nouvelles techniques, en premier lieu, la cybernétique (cyber : gouvernail) et le rétro-contrôle avec les limites inhérentes à ce type d’approche. En définitive, la Smart City peut être considérée comme une approche rationnelle pour gérer le phénomène urbain à une échelle encore plus grande, et pour en atténuer les effets négatifs déjà perceptibles à l’échelle actuelle. Il ne tient finalement qu’à nous de veiller à la solidité de notre édifice.</p>
          </article>
      }, {
        title: 'De Thomas More à Dubaï, existe-t-il encore des projets de cité utopique ?',
        img: 'http://img.aws.la-croix.com/2014/04/11/1135068/Des-XVIe-siecle-Thomas-More-decrit-Amaurote-capitale-pays-ideal-Utopia-Les-rues-mesurent-6-5-metres-large-habitants-travaillent-6-heures-jour-jouent-echecs-pendant-leur-temps-libre_2_730_491.jpg',
        author: 'Julien Duriez',
        category: 'Philosophie',
        source: 'Croix',
        content:
          <article>
            <p>Depuis que l’homme conçoit et construit son habitat, des penseurs se projettent dans un monde meilleur et imaginent la ville idéale.</p>
            <p>Certains de ces précurseurs sont restés des « architectes de papier », se limitant à la théorie, comme Thomas More ou le philosophe socialiste Charles Fourrier. D’autres, comme Niemeyer ou Le Corbusier, ont construit des villes de plusieurs centaines de milliers d’habitants.</p>
            <p>Leurs projets, à dimension universaliste, sont toujours le reflet des préoccupations de leur temps – réflexion politique dès l’antiquité, égalité et socialisme au XIXe siècle, écologie aujourd’hui.</p>
            <h3>Amaurote, la ville imaginaire d’Utopia, par Thomas More</h3>
            <p>Le concept de ville idéale apparaît dès l’antiquité. La réflexion de Platon dans La République se situe dans une « cité » modèle.</p>
            <p>Au XVIe siècle, Thomas More décrit Amaurote, la capitale d’un pays idéal : Utopia. « Le tracé d’une cité utopique est basé sur un idéal social », estime Martine Bouchier, professeur d’esthétique et chercheur au laboratoire Architecture ville urbanisme environnement (Lavue).</p>
            <p>Traversée par un fleuve, la ville imaginaire de Thomas More est située sur une île. Plantées d’arbres, les rues y mesurent 6,5 mètres de large, ses habitants travaillent tous 6 heures par jour et s’adonnent à des occupations culturelles ayant pour but d’élever leur esprit pendant leurs temps libres.</p>
            <p>Chez le philosophe anglais, qui écrit Utopia autant pour rêver à un futur idéal que pour critiquer son époque, la conception d’une cité utopique est liée à un idéal d’égalité.</p>
            <h3>Charles Fourrier influence la construction du familistère de Godin</h3>
            <p>Au XIXe, les modèles de villes idéales sont notamment influencés par la pensée socialiste utopique et les saint-simoniens. Entre autres projets, le philosophe Charles Fourrier imagine une « société harmonique », composée de trois millions de Phalanstères.</p>
            <p>Ces bâtiments, combinant habitat et loisir, doivent loger 400 familles au milieu d’un domaine de 400 hectares. L’industriel Jean-Baptiste André Godin s’en inspirera pour construire dans l’Aisne le familistère de Guise entre 1858 et 1883.</p>
            <h3>Letchworth, un exemple des « cités-jardins » du XIXe siècle</h3>
            <p>La réflexion menée par les architectes de la fin du XIXe siècle débouche sur l’apparition de la notion d’urbanisme. Alors que la seconde révolution industrielle bat son plein en Angleterre, certains prônent un retour à la nature. « Il faut alors remettre la campagne en ville », résume Martine Bouchier.</p>
            <p>L’urbaniste anglais Ebenezer Howard définit ainsi le concept de « cités-jardin », des villes de taille moyenne, composées de lotissements à faible densité et entourées de maraîchages censés subvenir aux besoins des urbains. Letchworth, au nord de Londres, sera construite dans les années 1900 sur ce modèle, qui influencera la construction de nombreuses autres villes de l’époque.</p>
            <p>Aujourd’hui, la nature en ville apparaît comme moins maîtrisée. « On assiste au retour du sauvage », analyse Martine Bouchier, qui prône, après le retour des plantes dans les villes contemporaines, celui des animaux, chevaux, oiseaux et même les « nuisibles ».</p>
            <h3>Chandigarh et Brasilia, deux villes de pouvoir</h3>
            <p>À la suite de la partition entre l’Inde et le Pakistan en 1947, l’État indien du Pendjab doit se trouver une nouvelle capitale. Conçue ex nihilo par plusieurs architectes, dont Le Corbusier, la ville de Chandigarh est divisée en soixante secteurs. Un système de circulation sophistiqué, hiérarchisant sept niveaux de routes dans la ville, est élaboré.</p>
            <p>Les bâtiments conçus par l’architecte franco-suisse sont aujourd’hui peu entretenus. Mais Chandigarh reste une des rares villes indiennes où il est encore facile de circuler.</p>
            <p>Le même Le Corbusier participe également à la conception de Brasilia, dirigée par les architectes Oscar Niemeyer et Lucio Costa. Comme pour Chandigarh, il s’agit de faire sortir de terre une capitale administrative en décentralisant le pouvoir. « Nous sommes bien avec ces deux villes dans un projet d’utopie. On peut lire la pensée moderne de leurs concepteurs dans les plans de la ville », estime Martine Bouchier.</p>
            <p>La nouvelle capitale brésilienne, siège de toutes les institutions du pays, est inaugurée en 1960. Conçue pour accueillir 500000 habitants, la ville nouvelle, sortie de terre en 1000 jours, en compte aujourd’hui plus de 2,5 millions.</p>
            <h3>Dubaï, la cité de tous les superlatifs</h3>
            <p>Des îles artificielles en forme de palmier, le Burj Khalifa – longtemps plus haute tour du monde –, et même une piste de ski : la capitale de l’émirat de Dubaï a accueilli les projets architecturaux les plus démesurés de ces dernières années. Financés grâce aux revenus de l’or noir, ils ont pour objectif de faire de Dubaï une destination touristique de référence pour préparer l’après-pétrole.</p>
            <p>Pour autant, Martine Bouchier ne retiendrait pas Dubaï comme un projet utopique : « il s’agit d’une société ultra-capitaliste, où les inégalités sont très fortes. Dubaï n’a à mon sens aucune dimension d’universalité ! »</p>
            <h3>La cité connectée de Songdo en Corée du Sud</h3>
            <p>Songdo, nouveau quartier d’affaires construit à l’ouest de Séoul sur un terrain gagné sur la mer, doit offrir, lorsqu’il sera terminé, 300 000 emplois et accueillir 65 000 habitants. Hyperconnectée, écologique, cette nouvelle cité est présentée comme le plus grand projet de développement urbain réalisé avec des fonds privés.</p>
            <p>Sans, une nouvelle fois, faire rêver Martine Bouchier. « Il s’agit d’une ville dédiée à l’économie. Ce genre de ville, que j’ai vu en Chine, ne me donne pas très envie d’y vivre… »</p>
            <p>La société américaine Gale, qui a investi 25 milliards d’euros dans Songdo, espère vendre ce concept clé en main de ville ultramoderne à une vingtaine d’agglomérations, notamment aux municipalités chinoises.</p>
            <h3>Lilypad, une ville flottante et écologique pour lutter contre la montée des eaux</h3>
            <p>D’ici 100 ans, le niveau des océans pourrait entraîner la submersion de 10 % des Pays Bas, environ 20 % du Bangladesh et 80 % des Maldives.</p>
            <p>Pour anticiper ce risque, l’architecte belge Vincent Callebaut présentait en 2008 le projet Lilypad, une cité flottante autosuffisante et écologique pouvant accueillir jusqu’à 50 000 habitants, reprenant ainsi le modèle de Thomas More de cité idéale sur une île.</p>
            <p>« La dimension écoclimatique et la gestion des déchets pourraient être la nouvelle utopie », pense Martine Bouchier, qui cite le projet Bellastock comme exemple. Avec le concours de 1000 étudiants en architecture, le collectif prévoit de construire, du 29 mai au 1 juin, une ville temporaire sur l’eau à Achères, dans les Yvelines, à partir de matériaux recyclés, avant de répéter l’exercice en Chine en septembre.</p>
          </article>
  }];

export default prisme4;
